 <link media="screen, projection" href="/central/css/products.css" rel="stylesheet">
  <div class="span-2">
  &nbsp;
  </div>
<div class="span-24 last">
<br />
<div class="hborder">
<div class="pagetitle">Change Password</div>
</div>
<div class="span-24 new-att last" style="position: relative; margin-top: 10px; width: 400px; background-color: #FAFAEE; padding-top: 20px; ">
    <div><?php echo $this->msg; ?> </div>
  <form name="customer_form" action="" method="POST" enctype="multipart/form-data">
   <table>
       
<?php echo $this->form->user_id; ?>
        <?php echo $this->form->current_password; ?>
    <?php echo $this->form->password; ?>
<?php echo $this->form->submit; ?>
  </table>

  </form>
  </div>
</div>