 <!-- link media="screen, projection" href="<?php //echo $this->baseUrl(); ?>/css/products.css" rel="stylesheet" -->
<style type="text/css">
    .box{
        background-color: #F00;
        color: white;
    }
</style>
<div class="span-17">&nbsp;</div>
 <div class="span-20 last box" style="position: relative; top:100px;">
<div><h2>User deleted</h2> 
    <center><h3>
            <span style="color: #FFF"><?php echo $this->user_remove_report ?></span>   
    </h3>     
    </center>    
</div>
 </div> 

<script type="text/javascript">
  $(document).ready(function() {
  
             //  window.location = '<?php echo $this->baseUrl();?>/admin/category/list';
             
           });
</script>