<style>
 .set-table{
 float:left;
 table-layout:fixed;
}
.set-tab{
	margin-top: 8%;
}
</style>  

 <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-9 col-md-16">
                         <h3></h3>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit User</div>
                            
                                </div>
                            </div>
                        </div>
						
						<div class="panel-body">
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                <form action="" method="post" enctype="multipart/form-data" role="form">
				           <div class="table-responsive set-tab"> 
						   <table class="table table-striped table-bordered table-hover set-table">
												<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
											
													<?php echo $this->form->user_name ?>
													<?php echo $this->form->email ?>
														<input type="hidden" name="user_id" value="<?php echo $this->user_id?>">
                                                    <!--<?php echo $this->form->role?>-->
                                                    <tr><td>&nbsp;</td><td>
                                                    <?php echo $this->form->submit?>
											</td></tr>
                                            </table>
											</div><!--div responsive end-->
                  	</form>	
                                
                                
                                </div>
                            </div>
						
                        <a href="#">
                            <div class="panel-footer">
                            </div>
                        </a>
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 </script>