<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" /> 

    <title>netefct</title> 
    <link type="byronthomas/fav-icon.png" href="favicon.ico" rel="icon" />
    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-3/css/bootstrap/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/css/plugins/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-3/css/fontawesome/font-awesome.min.css" rel="stylesheet" type="text/css">
 <!-- DataTables CSS -->
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/css/plugins/dataTables.bootstrap.css" rel="stylesheet">
      <link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet">
    
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

	<!-- custom css for admin.css-->
	<link href="<?php echo $this->baseUrl(); ?>/css/colinkr/admin.css" rel="stylesheet">
    
	
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <div id="wrapper">
 <?php echo $this->render("header.phtml"); ?>
 <?php echo $this->layout()->content; ?>      
    </div>
    <!-- /#wrapper -->

    <!-- jQuery Version 1.11.0 -->
    <script src="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/js/plugins/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/js/plugins/morris/raphael.min.js"></script>
 
    <!-- Custom Theme JavaScript -->
    <script src="<?php echo $this->baseUrl(); ?>/css/bootstrap-3.2.0/themes/sb-admin-2/js/sb-admin-2.js"></script>
	
    <!-- ckeditor javascript libraries -->
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/ckeditor/adapters/jquery.js"></script>
    
    
    
</body>

</html>