<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $this->escape($this->title); ?></title>

    <!-- Bootstrap -->
    <link href="<?php echo $this->baseUrl(); ?>/css/admin/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <link href="<?php echo $this->baseUrl(); ?>/css/admin/admin.css" rel="stylesheet">


  </head>
  <body>

    <div class="container"><!--main container start -->
    <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <div class="header">
        <ul class="nav nav-pills pull-right">
        <li class="active"><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
        </ul>
        <h3 class="text-muted">Welcome to Netefct</h3> 
     </div>
     <hr></hr>
      <div class="jumbotron">
        <!--<h1 class="set-img"><img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/default/logo.png" alt="logo"></h1>-->
        <p class="lead">
          <?php echo $this->layout()->content; ?>       
        </p>
      </div>
      <hr></hr>
    <div class="footer">
        <p>&copy; netefct 2015</p>
      </div>
      </div>
      </div>
   <!-- <?php echo $this->layout()->content; ?>-->
     </div> <!--main container end-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<?php echo $this->baseUrl(); ?>/js/admin/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo $this->baseUrl(); ?>/js/admin/bootstrap.min.js"></script>

<script>
$(function(){
//alert("Jquery is working");

});
</script>

  </body>
</html>