<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>JJ Smith</title> 
    <link type="byronthomas/fav-icon.png" href="favicon.ico" rel="icon">
    <!-- Bootstrap Core CSS -->
   </head>

<body>

 <div id="wrapper">
 <?php echo $this->layout()->content; ?>      
    </div>
 	
</body>

</html>