<style>
 .set-table{
 float:left;
}
</style>    
    <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                         <h3></h3>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-video-camera fa-5x"></i>
                                </div>
													
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Strip Banner List</div>
                            
                                </div>
                            </div>
                        </div>
						
						 <div class="panel-body">
                               
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                <div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered  set-table" width="100%">
														<thead>
														
														<?php 

if($this->msg == 1){
$this->msg = "<div class='alert alert-success'>Strip Banner Deleted</div>";	
} 

if($this->msg == 3){
$this->msg = "<div class='alert alert-danger'>You cant' delete all strip banner must keep at least one Main Strip Banner </div>";	
} 

if($this->msg == 2){
$this->msg = "<div class='alert alert-danger'>Please try again!</div>";	
} 
if(isset($this->msg)){

?>														<tr id='msg'><td colspan='6'><?php echo $this->msg ?></td></tr>
<?php } ?>
													  		
														
															<tr>
																<th style="text-align:center;">Banner</th>
																<th style="text-align:center;">Target Url</th>
																<!--<th style="text-align:center;">Message</th>-->
																
																<th style="text-align:center;">Main</th>
																<th style="text-align:center;">Edit </th>
																<th style="text-align:center;">Delete</th>
                                                        	</tr>
														</thead>		
														<tbody>
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
<tr class="odd gradeX">
												
	<td style="text-align:center;" colspan="5">
<!-- div  style="position: relative; width: 200px; height: 200px" -->
<img style="max-width:100%; max-height: 100%" src="<?php echo $this->baseUrl(); ?>/images/strip-banner-images/original/<?php echo $item['banner_img'] ?>" alt="" />
<!-- /div -->
</tr>
 
															
															
															</td>
														<tr class="odd gradeX">
												
												
														<td style="text-align:center;" colspan="2">
															<?php echo $item['target_url'] ?>
															</td>
															
                                                            

														                <td style="text-align:center;">
														 <?php 
																if($item['is_main'] == 1) { ?>
															   <i>Yes</i> 
																<?php
																}else{
																	?>
																<i> No</i>
																										   
																<?php 	
																} ?></td>                                        

														<td style="text-align:center;"><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/strip-banner/edit-strip-banner/sb_id/<?php echo $item['sb_id'] ?>">Edit</a></td>
															 <td  style="text-align:center;"><a class="btn btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['sb_id'] ?> )" href="">Delete </a></td>
														</tr>
															<?php endforeach; ?>
															<tr><td colspan='9' style="text-align:center;">
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no Banner List!</h4></td></tr>
															<?php } ?>
														</tbody>

						 								</table>
														</div><!-- div responsive end-->
												</div>

                               
                                
                                
                                </div>
				 		
                        <a href="#">
                            <div class="panel-footer">
                                
								 </a>
                            </div>
                       
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
 
 function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Strip Banner! " ); 
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/strip-banner/delete-strip-banner/id/" + id);    
	} else {
	return false;
	}
	}
 </script>