  <script src="<?php echo $this->baseUrl();?>/js/admin/ckeditor/ckeditor.js"></script>
 <div class="row">
  <div class="col-md-12">
  <div class="page-title">Edit  <strong><?php echo $this->escape($this->name); ?></strong> Testimonial</div>
  </div><!-- /.col-md-12-->
 </div><!-- /.row -->

 <div class="row">
   <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
  <div class="col-md-6">
    <table class="table space-mangead">
     <tr id='msg'><td ><?php echo $this->msg ?></td></tr>
      <tr><td><strong>Image:</strong></td></tr><td>
      <img src="<?php echo $this->baseUrl();?>/images/user/testimonials/500X500/<?php echo $this->image;?>" alt="image" style="float:left; width:300px"/></td>
      <tr><td><strong>Change Image:</strong>  <?php echo $this->form->image1; ?></td></tr>
  </table>
</div>
 <div class="col-md-6">
    <table class="table space-mangead">
       <tr><td><strong>First Name:</strong></td></tr>
      <?php echo $this->form->first_name; ?>
      <tr><td><strong>Last Name::</strong></td></tr>
      <?php echo $this->form->last_name; ?>
      <tr><td><strong>Email:</strong></td></tr>
      <?php echo $this->form->email; ?>
      <tr><td><strong>Testimonial:</strong></td></tr>
      <?php echo $this->form->short_description; ?>
      <tr><td > <?php echo $this->form->submit?></td></tr>
     </table>
    </form>
  </div><!-- /.col-md-12-->
 </div><!-- /.row -->

<script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('tr#msg').hide();

    <?php  } else{
    ?>
      $('tr#msg').show().delay(3000).hide('slow');

    <?php } ?>
 // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
               CKEDITOR.replace( 'editor1' );
 }

 </script>