<div id="page-wrapper">
    <div class="row">
       <div class="col-lg-12">
            <div class="page-title"><strong>User Visits by User Type</strong></div>            
       <br />
       <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example">
		<thead>
            <tr>
    			<th style="text-align:center;"> User Type</th>
    			<th style="text-align:center;"> Visits</th>
            </tr>
		</thead>
        <tbody>
    		<?php	 	
    		//printing each row.
    		foreach ($this->by_user_type->getRows() as $row) { 	 	
    			echo "<tr><td>".$row[0]."</td><td>".$row[1]."</td></tr>"; 	 
    		}	 
            ?>
        </tbody>	 
        </table>
       </div>
       </div>
      </div>
      <br />
      <div class="row">
       <div class="col-lg-12">
       <div class="page-title"><strong>User Visits by Date</strong></div>
       <br />
       <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example">	 
		<thead>
            <tr>
                <th style="text-align:center;"> Date</th>
    			<th style="text-align:center;"> Visits</th>
    	   </tr>
        </thead>
        <tbody>	 	
    		<?php	 	
    		//printing each row.
    		foreach ($this->by_date->getRows() as $row) { 	 	
    			echo "<tr><td>".date('m/d/Y', strtotime($row[0].''))."</td><td>".$row[1]."</td></tr>";
    		}	 
        ?>
        </tbody>	 	
        </table>
       </div></div>
    </div>
    <div class="row">
        <div class="col-lg-12">
       
       </div>
    </div>
</div>

<script type="text/javascript">
 $(function () { 
        $('.dataTables-example').dataTable();
 });
 </script>