<div id="page-wrapper">
    <div class="row">
       <div class="col-lg-12">
            <h1>User Visits by User Type</h1>
       <br />
            <table class="responsive dynamicTable display table table-bordered">
		<tr>	 
		<?php	 
		//Printing column headers
    		foreach($this->by_user_type->getColumnHeaders() as $header){
    			echo "<td><b>".$header['name']."</b></td>"; 	 	
    			}	 	
    		?>	 	
    	</tr>	 	
    		<?php	 	
    		//printing each row.
    		foreach ($this->by_user_type->getRows() as $row) { 	 	
    			echo "<tr><td>".$row[0]."</td><td>".$row[1]."</td></tr>"; 	 
    		}	 
        ?> 	
        	 
        </table>
       </div>
      </div>
      <div class="row">
       <div class="col-lg-12">
       <h1>User Visits by Date</h1>
       <br />
            <table class="responsive dynamicTable display table table-bordered">	 
		<tr>	 
		<?php	 
		//Printing column headers
    		foreach($this->by_date->getColumnHeaders() as $header){
    			echo "<td><b>".$header['name']."</b></td>"; 	 	
    			}	 	
    		?>	 	
    	</tr>
        	 	
    		<?php	 	
    		//printing each row.
    		foreach ($this->by_date->getRows() as $row) { 	 	
    			echo "<tr><td>".date('Y-m-d', strtotime($row[0].''))."</td><td>".$row[1]."</td></tr>";
    		}	 
        ?>
        	 	
        </table>
       </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
       
       </div>
    </div>
</div>