<!--
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/tinymce/js/tinymce/tinymce.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
 
<script>tinymce.init({
	selector:'textarea',
      theme: "modern",
	plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
  });
</script> -->

<script src="<?php echo $this->baseUrl();?>/js/admin/ckeditor/ckeditor.js"></script>
<style>
.space-mangead{
	margin-top: 3%;
}
.set-save-draft{
	float:left; 
	margin: 0px 322px 0px 0px;
}
.set-txt{
	height: 30px;
    width: 258px;
}
#url-label{
	display:none;	
}
.set-slug{
	float:left;
    padding: 3px 6px 0 0;
}

.update-btn{
margin-bottom:10px;
float:left;
}
</style>

<div class="row">
   <div class="col-lg-12">
        <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post"> <i class="btn btn-md btn-primary"> New Blog Post</i></a>
        &nbsp;
        <a href="<?php echo $this->baseUrl(); ?>/admin/posts/posts-list"> <i class="btn btn-md btn-primary"> Blog Posts List</i></a>
   </div>
</div>
<br/>

<div class="row">
 <div class="col-md-12">
 <div class="page-title"><strong>Edit Blog Post</strong></div>
</div><!-- /.col-md-12-->
</div><!-- /.row -->


    <div class="row">
        <div class="col-md-12">
                                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
									
                                       	<table class="table space-mangead">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg; ?></td></tr>
										 
         							     
									   <!--<?php echo $this->form->csrf ?>-->				
                                       
									   <?php echo $this->form->heading; ?>
									   <tr><td><label>* Blog Post Url Slug</label></td><td><p class="set-slug"><?php echo $this->post_url; ?></p><?php echo $this->form->url; ?></td></tr>
									   <tr><td><label>* Current Url Slug</label></td><td><p class="set-slug"><?php echo $this->post_url; ?><span id="label1" ><?php echo $this->url_slug; ?></span></p></td></tr>
                                       <tr><td><label>Blog Post Image:</label></td>
                                       <td>
                                        <?php if(!empty($this->image)) {?>
                                            <img src="<?php echo $this->baseUrl();?>/images/user/posts/200X200/<?php echo $this->image;?>" alt="<?php echo $this->image;?>" width="160" height="100"/>
                                            <?php } else {?>
                                            <img src="<?php echo $this->baseUrl();?>/images/user/posts/200X200/placeholder.png" alt="placeholder" width="160" height="100"/>
                                            <?php } ?>
                                        
                                       </td></tr>									  
                                       <input type="hidden" name="post_id" value="<?php echo $this->post_id?>"/>
                                       <tr><td style="width: 230px;"><label>Change 800 pixel wide image</label></td>
                                       <td><?php echo $this->form->image;?></td></tr>							    
                                         <?php //echo $this->form->description; ?>
                                         <tr>
                                            <td colspan="2">
                                                <textarea contenteditable="true" cols="80" rows="24" class="form-control" id="description" name="description"></textarea>
                                            </td>
                                         </tr>
										 <?php echo $this->form->is_comment; ?>
										 <?php echo $this->form->categories; ?>
										 <?php echo $this->form->tags; ?>
                                       <tr>
                                       <td colspan="2">
                                        <!--<?php echo $this->form->submit?>-->
										<button class="btn btn-md btn-primary pull-right" value="0" name="submit" type="submit">Update and Continue</button>
										<button class="btn btn-md btn-primary pull-right" value="1" name="submit" type="submit" style="margin-right: 20px;">Save as Draft</button>										
										</td></tr>   
                                        </table>
                                   </form>
        </div>
    </div>
    

 <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
        
        CKEDITOR.replace('description');
 }

// make slug from title
$("#heading").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);
		$("#label1").text($(this).val());
});
 
  // make custom slug
$("#url").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);
	 	$("#label1").text($(this).val());
});

$("#url").keyup(function(){
   $("#label1").text($(this).val());   
});

$("#heading").keyup(function(){
		var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
   $("#label1").text($(this).val());   
});
	
 </script>