<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/tinymce/js/tinymce/tinymce.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
 
<script>tinymce.init({
	selector:'textarea',
      theme: "modern",
	plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
  });
</script>

<style>
.space-mangead{
	margin-top: 3%;
}
.set-save-draft{
	float:left; 
	margin: 0px 322px 0px 0px;
}
.set-txt{
	height: 30px;
    width: 258px;
}
#url-label{
	display:none;	
}
.set-slug{
	float:left;
    padding: 3px 6px 0 0;
}

.update-btn{
margin-bottom:10px;
float:left;
}
</style>

<!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			 <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/blog/new-post"> <i class="btn btn-sm btn-primary"> New Blog Post</i></a></td>
                    <td> <a href="<?php echo $this->baseUrl(); ?>/admin/blog/posts-list"> <i class="btn btn-sm btn-primary"> Blog Posts List</i></a></td>
					</tr>
                    </table>
                 </div>
                 </div><!-- ./ row 1-->
			<div class="col-lg-11">
          
                    	
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit Blog Post</div>
                            
                                </div>
                            </div>
                        </div>
                            <div class="panel-body">
                             
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  <div id="basic_info">
                                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
									<div class="table table-responsive">
                                       	<table class="table-responsive table table-striped table-bordered table-hover space-mangead">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg; ?></td></tr>
										<!--<tr><td colspan="2"><strong><a href="#">Basic Information</a></strong></td></tr>--> 
         							     
									   <!--<?php echo $this->form->csrf ?>-->				
                                       
									   <?php echo $this->form->heading; ?>
									   <tr><td><Label>* Blog Post Url Slug</Label></td><td><p class="set-slug"><?php echo $this->post_url; ?></p><?php echo $this->form->url; ?></td></tr>
									   <tr><td><Label>* Current Url Slug</Label></td><td><p class="set-slug"><?php echo $this->post_url; ?><span id="label1" ><?php echo $this->url_slug; ?></span></p></td></tr>
                                       <tr><td><Label>Blog Post Image:</Label></td><td><? if($this->post_id>0){?><img src="<?php echo $this->baseUrl();?>/images/posts/500X500/<?php echo $this->image;?>" alt="" style="float:left; width:150px;"/><?php }?></td></tr>									  
                                       <input type="hidden" name="post_id" value="<?php echo $this->post_id?>"/>
                                       <tr><td><Label>Change 800 pixel wide image</Label></td><td><?php echo $this->form->image;?></td></tr>							    
                                         <?php echo $this->form->description; ?>
										 <?php echo $this->form->is_comment; ?>
										 <?php echo $this->form->categories; ?>
										 <?php echo $this->form->tags; ?>
                                       <tr><td>&nbsp;</td><td>
                                        <!--<?php echo $this->form->submit?>-->
										<button class="btn btn-lg btn-primary update-btn" value="0" name="submit" type="submit">Update and Continue</button>
										<button class="btn btn-lg btn-primary set-save-draft" value="1" name="submit" type="submit">Save as Draft</button>
										
										</td></tr>   
                                        </table>
										</div>
                                   </form>
	                            </div>
                            </div>
                      
                    </div>
                       <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

 

 <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }

// make slug from title
$("#heading").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);
		$("#label1").text($(this).val());
});
 
  // make custom slug
$("#url").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);
	 	$("#label1").text($(this).val());
});
$("#url").keyup(function(){
   $("#label1").text($(this).val());   
});
$("#heading").keyup(function(){
		var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
   $("#label1").text($(this).val());   
});
	
 </script>