<div class="row">
    <div class="col-md-12">
        <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post"> <i class="btn btn-md btn-primary">New Blog Post</i></a>
    </div><!-- /.col-md-12-->
</div><!-- /.row -->

<br />
<div class="row">
 <div class="col-md-12">
 <div class="page-title"><strong>Posts List</strong></div>
</div><!-- /.col-md-12-->
</div><!-- /.row -->
<br />

    <div class="row">        
                    <div class="col-lg-12">
                    
							
   <!-- <form class="form-inline" action="<?php //echo $this->baseUrl()?>/admin/blog/posts-list" method="post">
   <div class="form-inline">
   <input type="text" class="form-control" id="query_string" placeholder="Search..." name="query_string"/>
   &nbsp;  <?php //echo $this->form->search_type?> &nbsp; 
&nbsp;&nbsp; <button type="submit" class="btn btn-warning">Search</button>	
		</div>
		</form> -->
    <div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
		<br />
                                <div class="table-responsive">
													<table class="table table-striped table-bordered table-hover" id="dataTables-example">
														<thead>
														<tr>
																<th style="text-align:center;"> Title</th>
																<th style="text-align:center;"> Author</th>
																<th style="text-align:center;"> Tags</th>
																<th style="text-align:center;"> Publish Date</th>
																<th style="text-align:center;">Edit </th>
																<th style="text-align:center;">Delete</th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->data)){ ?>
													
														<?php foreach ($this->data as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['heading'] ?>
															</td> 
															<td style="text-align:center;">
															<?php if($item['user_id'] > 0){
																  ?>
													       <p>admin</p> 
														     <?php
														     }else{
															  ?>
															<p>unknown</p>
																								   
														     <?php 	
															}
															
															?>
															</td>
															<td style="text-align:center;">
															<?php echo $item['tags'] ?>
															</td>
															<td style="text-align:center;">
															<?php echo $item['date_published'] ?>
															</td>

															
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/posts/edit-post/post_id/<?php echo $item['post_id'] ?>">Edit</a></td>
															 <td  style="text-align:center;"><a class="btn btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['post_id'] ?> )" href="">Delete </a></td>
														</tr>  
															<?php endforeach;  } ?>
														</tbody>

						 								</table>
                        </div><!-- div responsive end-->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->


  <script language="Javascript" type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show();
		<?php } ?>
        
        $('#dataTables-example').dataTable();
 }
 
  function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Post! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/posts/delete-post/id/" + id);    
	} else {
	return false;
	}
	}
 </script>