<!--
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/tinymce/js/tinymce/tinymce.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://code.jquery.com/jquery-1.7.2.js"></script> 

 
<script>tinymce.init({
	selector:'textarea',
      theme: "modern",
	plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
  });
</script> -->

<script src="<?php echo $this->baseUrl();?>/js/admin/ckeditor/ckeditor.js"></script>
<style>
.space-mangead{
	margin-top: 3%;
}
.set-save-draft{
	float:right; 
	margin: 0px 322px 0px 0px;
}
.set-txt{
	height: 30px;
    width: 258px;
}
#url-label{
	display:none;	
}
.set-slug{
	float:left;
    padding: 3px 6px 0 0;
}
</style>

<div class="row">
    <div class="col-lg-12">
	   <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-md-12">
                 	<a href="<?php echo $this->baseUrl(); ?>/admin/posts/posts-list"> <i class="btn btn-sm btn-primary"> Posts List</i></a>
                 </div>
       </div><!-- ./ row 1-->
    </div>
</div>

<div class="row">
 <div class="col-md-12">
 <div class="page-title"><strong>Add New Post</strong></div>
</div><!-- /.col-md-12-->
</div><!-- /.row -->

<div class="row">
 <div class="col-md-12">
                                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
									
                                       	<table class="table space-mangead">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										
									   <?php echo $this->form->heading; ?>
									   <tr><td><label>* Post Url Slug</label></td><td><p class="set-slug"><?php echo $this->post_url; ?></p><?php echo $this->form->url; ?></td></tr>
                                       <tr><td><label>Upload 800 pixel wide image</label></td><td><?php echo $this->form->image;?></td></tr>							    
                                         <?php //echo $this->form->description; ?>
                                         <tr>
                                            <td colspan="2">
                                                <textarea contenteditable="true" cols="80" rows="24" class="form-control" id="description" name="description"></textarea>
                                            </td>
                                         </tr>
										 <?php echo $this->form->is_comment; ?>
										 <?php echo $this->form->categories; ?>
										 <?php echo $this->form->tags; ?>
                                       <tr>
                                       <td colspan="2">
                                        <button class="btn btn-lg btn-primary" style="margin-right: 20px;" onclick="return confirmDelete" value="0" name="submit" type="submit">Publish</button>
										<button class="btn btn-lg btn-primary" value="1" name="submit" type="submit">Save as Draft</button>
										</td></tr>   
                                        </table>
                                   </form>
	                            </div>
                            </div>

 <script type="text/javascript">
    window.onload = function () { 
     <?php if(!isset($this->msg)){ ?>
    			$('tr#msg').hide();
    			
    		<?php  } else{
    		?>
    			$('tr#msg').show();
    		<?php } ?>
     

 // make slug from title
$("#heading").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);        
});
 
  // make custom slug
$("#url").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);        
});
  
         //CKEDITOR.dtd.$editable.textarea = 1;
            //CKEDITOR.disableAutoInline = true;
            //CKEDITOR.inline('description');
            CKEDITOR.replace('description');            
}
    </script>
