<style>
 .set-table{
 float:left;
}
</style>    
    <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
				<div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                 	<table class="table">
                    <tr><td> <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post"> <i class="btn btn-sm btn-primary">New Blog Post</i></a></td>
                    </tr>
                    </table>
                 </div>
                 </div><!-- ./ row 1-->
                    <div class="col-lg-12">
                         
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-users fa-5x"></i>
                                </div>							
							
							<div class="col-md-7">
							
							<form class="form-inline" action="<?php echo $this->baseUrl()?>/admin/blog/posts-list" method="post">
   <div class="form-inline">
   <input type="text" class="form-control" id="query_string" placeholder="Search..." name="query_string"/>
   &nbsp;  <?php echo $this->form->search_type?> &nbsp; 
&nbsp;&nbsp; <button type="submit" class="btn btn-warning">Search</button>	
		</div>
		</form>
		</div>
								
                                <div class="col-xs-3 text-right">
                                    <div class="huge">Posts List</div>
                            
                                </div>
                            </div>
                        </div>
						
						 <div class="panel-body">
                               <!-- <span class="pull-left">Use buttons for operations</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>-->
                                <div class="clearfix">
                                <div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered  set-table" width="100%">
														<thead>
														<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
															<tr>
																<th style="text-align:center;"> Title</th>
																<th style="text-align:center;"> Author</th>
																<th style="text-align:center;"> Tags</th>
																<th style="text-align:center;"> Publish Date</th>
																<th style="text-align:center;">Edit </th>
																<th style="text-align:center;">Delete</th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td>
															<?php echo $item['heading'] ?>
															</td> 
															<td style="text-align:center;">
															<?php if($item['user_id'] > 0){
																  ?>
													       <p>admin</p> 
														     <?php
														     }else{
															  ?>
															<p>unknown</p>
																								   
														     <?php 	
															}
															
															?>
															</td>
															<td style="text-align:center;">
															<?php echo $item['tags'] ?>
															</td>
															<td style="text-align:center;">
															<?php echo $item['date_published'] ?>
															</td>

															
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/posts/edit-post/post_id/<?php echo $item['post_id'] ?>">Edit</a></td>
															 <td  style="text-align:center;"><a class="btn btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['post_id'] ?> )" href="">Delete </a></td>
														</tr>  
															<?php endforeach; ?>
															<tr><td colspan='9' style="text-align:center;">
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no Posts List.</h4></td></tr>
															<?php } ?>
														</tbody>

						 								</table>
														</div><!-- div responsive end-->
												</div>

                                </div>
				 		
                        <a href="#">
                            <div class="panel-footer">
                                
								 </a>
                            </div>
                       
                    </div>
                </div>
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 
  function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Post! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/posts/delete-post/id/" + id);    
	} else {
	return false;
	}
	}
 </script>