 
 <div class="row">
  <div class="col-md-12">
  <div class="page-title">Edit  <strong><?php echo $this->escape($this->name); ?></strong> Image Block</div>
  </div><!-- /.col-md-12-->
 </div><!-- /.row -->

 <div class="row">
  <div class="col-md-12">
   <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
    <table class="table space-mangead">
     <tr id='msg'><td ><?php echo $this->msg ?></td></tr>
      <tr><td><strong>Block Image:</strong></td></tr><td><img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/200X200/<?php echo $this->block;?>" alt="image-block" style="float:left; width:150px;"/></td>
  
      <tr><td><strong>Image Name:</strong></td></tr>
      <?php echo $this->form->name; ?>
      <tr><td><strong>Image Link:</strong></td></tr>
      <?php echo $this->form->link; ?>
      <tr><td><strong>Image Caption:</strong></td></tr>
      <?php echo $this->form->caption; ?>
      <tr><td><strong>Change Image:</strong></td></tr>
      <tr><td><?php echo $this->form->block; ?></td></tr>
      <tr><td><strong>Disable Link:</strong></td></tr>
      <?php echo $this->form->disable_link; ?>
      <tr><td > <?php echo $this->form->submit?></td></tr>
     </table>
    </form>
  </div><!-- /.col-md-12-->
 </div><!-- /.row -->

<script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('tr#msg').hide();

    <?php  } else{
    ?>
      $('tr#msg').show().delay(3000).hide('slow');

    <?php } ?>
 }
 </script>