<div class="row">
    <div class="col-lg-12">
        <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/index"> <i class="btn btn-md btn-primary">Image Blocks List</i></a>
    </div>
</div>
<br />
<div class="row">
 <div class="col-md-12">
 <div class="page-title">Edit  <strong><?php echo $this->escape($this->name); ?></strong> Image Block</div>
</div><!-- /.col-md-12-->
</div><!-- /.row -->

 <div class="row">
   <div class="col-md-12">
    
    <div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
		<br />
   <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
  <div class="col-md-6">
    <table class="table space-mangead">
     
      <tr><td><strong>Block Image:</strong></td></tr><td>
      <img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/500X500/<?php echo $this->block;?>" alt="image-block" style="float:left; width:300px"/></td>
      <tr><td><strong>Change Image:</strong>  <?php echo $this->form->block; ?></td></tr>
  </table>
</div>
 <div class="col-md-6">
    <table class="table space-mangead">
       <tr><td><strong>Image Name:</strong></td></tr>
      <?php echo $this->form->name; ?>
      <tr><td><strong>Image Link:</strong></td></tr>
      <?php echo $this->form->link; ?>
      <tr><td><strong>Image Caption:</strong></td></tr>
      <?php echo $this->form->caption; ?>
      <tr><td><strong>Disable Link:</strong></td></tr>
      <?php echo $this->form->disable_link; ?>
      <tr><td > <?php echo $this->form->submit?></td></tr>
     </table>
    </form>
  </div>
  </div>
  <!-- /.col-md-12-->  
 </div><!-- /.row -->

<script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('#msg').hide();

    <?php  } else{
    ?>
      $('#msg').show().delay(3000).hide('slow');

    <?php } ?>
 }
 </script>