
<style>
#progressOverlay .progress {
    position:relative;
    width:80%;
    top:50%;
    margin:0 auto;
}
#progressOverlay {
    position:relative;
    height:100%;
}
</style>

 <div class="row">
 <div class="col-md-12">
 <div class="page-title">Manage Image Blocks</div>
<hr/>
 <div class="table-responsive ">
                                        <table class="table table-bordered space-mangead">
                                        <tr><th>Image  Block 1</th><th>Data</th><th>Location</th></tr>
                                        <tr id='msg'><td colspan='3'><?php echo $this->msg ?></td></tr>
    <tr>
    <td >
   <center>
   <div>
     <?php if(strlen($this->block1) > 4 ){ ?>
    <img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/user/image-blocks/files/thumbnail/<?php echo $this->block1 ?>"/>
    <?php }else{ ?>
    <img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/admin/placeholder200X200.png"/>
    <?php }?>
       </div>
       </center>
    </td>
<td rowspan="2">
  <div class="form-group">
    <label for="capation1">Caption</label>
    <input type="input" class="form-control" id="caption1" placeholder="Caption">
  </div>
  <div class="form-group">
    <label for="link1">Link</label>
    <input type="input" class="form-control" id="link1" placeholder="Link URL as http://website.com">
  </div>
  <div class="form-group">
    <button class="btn btn-warning">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Update Record</span>
    </button>
    </div>
 <div>
 </div>
  </td>

<td class="cell-compact">
 <div>
  <img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/admin/image-block-location/block1-thumbnail.png"/>
 </div>
  </td>

    </tr>

<tr>
<td>
<center>
      <div class="upload-buttons">
    <span class="btn btn-success fileinput-button">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Update Image 1</span>
        <!-- The file input field used as target for the file upload widget -->
        <input id="block1" type="file" name="files[]">
    </span>
    </div>
       <br>
    <!-- The global progress bar -->
    <!-- div id="progress1" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div -->
    <!-- The container for the uploaded files -->
    <div id="files1" class="files"></div>
  </center>
  </td>

<td>
<div>
Image Block Width: 300 pixels<br/>
Image Block Height: 300 pixels<br/>
</div>
</td>
</tr>
<!--/ END OF BLOCK1 -->
</table>

                                        <table class="table table-bordered space-mangead">
                                        <tr><th>Image Block 2</th><th>Data</th><th>Location</th></tr>
                                        <tr id='msg'><td colspan='3'><?php echo $this->msg ?></td></tr>
    <tr>
    <td >
   <center>
   <div>
     <?php if(strlen($this->block1) > 4 ){ ?>
    <img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/user/image-blocks/files/thumbnail/<?php echo $this->block1 ?>"/>
    <?php }else{ ?>
    <img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/admin/placeholder200X200.png"/>
    <?php }?>
       </div>
       </center>
    </td>
<td rowspan="2">
  <div class="form-group">
    <label for="capation1">Caption</label>
    <input type="input" class="form-control" id="caption1" placeholder="Caption">
  </div>
  <div class="form-group">
    <label for="link1">Link</label>
    <input type="input" class="form-control" id="link1" placeholder="Link URL as http://website.com">
  </div>
  <div class="form-group">
    <button class="btn btn-warning">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Update Record</span>
    </button>
    </div>
 <div>
 </div>
  </td>

<td class="cell-compact">
 <div>
  <img class="img-responsive" src="<?php echo $this->baseUrl(); ?>/images/admin/image-block-location/block1-thumbnail.png"/>
 </div>
  </td>

    </tr>

<tr>
<td>
<center>
      <div class="upload-buttons">
    <span class="btn btn-success fileinput-button">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Update Image 1</span>
        <!-- The file input field used as target for the file upload widget -->
        <input id="block1" type="file" name="files[]">
    </span>
    </div>
       <br>
    <!-- The global progress bar -->
    <div id="progress1" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
    <!-- The container for the uploaded files -->
    <div id="files1" class="files"></div>
  </center>
  </td>

<td>
<div>
Image Block Width: 300 pixels<br/>
Image Block Height: 300 pixels<br/>
</div>
</td>
</tr>
<!--/ END OF BLOCK1 -->
</table>

    </div>
</div>
</div><!-- /.row -->

<script>
$(function () {

 <?php if(!isset($this->msg)){ ?>
            $('tr#msg').hide();

        <?php  } else{
        ?>
            $('tr#msg').show();
        <?php } ?>
    'use strict';
    // Change this to the location of your server-side upload ` handler:
    var url = "<?php echo $this->baseUrl(); ?>/images/user/image-blocks/index.php";
    //var url = "<?php //echo $this->baseUrl(); ?>/members/upt";
    $('#block1').fileupload({
        url: url,
        dataType: 'json',
        done: function (e, data) {

            $.each(data.result.files, function (index, file) {
                $('<p/>').text(file.name).appendTo('#files1');

            var id =  1;
            $.post("<?php echo $this->baseUrl()?>/admin/image-blocks/update-block/", {image: file.name, id: id},
    function(data){
        if(data){
        location.reload();
        }else{
            alert("Please try again to upload image");
            }

        });
            });
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress1 .progress-bar').css(
                'width',
                progress + '%'
            );
        }
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');
});
</script>