<div class="row">
    <div class="col-lg-12">
        <a href="<?php echo $this->baseUrl(); ?>/admin/post-comments/index"> <i class="btn btn-md btn-primary">Post Comments List</i></a>
    </div>
</div>
<br />
<div class="row">
 <div class="col-md-12">
 <div class="page-title"><strong>Edit Comment</strong></div>
</div><!-- /.col-md-12-->
</div><!-- /.row -->

<div class="row">
    <div class="col-md-12">
    
    <div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
		<br />
        
        <form action="" method="post">
             	 <?php echo $this->form->csrf ?>
                               <table class="table table-striped table-hide table-hover space-mangead">                                   	
							     <input type="hidden" name="pc_id" value="<?php echo $this->pc_id ?>" />
									  <tr><td><label> Name:</label></td>
									  <td><?php echo $this->form->name; ?></td></tr>
                                       <tr><td> <label > Email:</label></td>
									   <td><?php echo $this->form->email; ?></td></tr>
										<tr><td> <label >Comment:</label></td>
										<td><?php echo $this->form->comment; ?></td></tr>
										 <tr><td colspan="2">
                                        <button type="submit" class="btn btn-primary pull-right">Save</button>
										</td></tr>   
                                        </table>
            </form>		
    </div>
 </div>
 
 <script type="text/javascript">
    window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('#msg').hide();
			
		<?php  } else{
		?>
			$('#msg').show();
		<?php } ?>
 
 }
 </script>