<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                         
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-comments fa-4x"></i>
                                </div>
								
                                <div class="col-xs-10 text-right">
                                    <div class="huge">Edit Comment</div>
                            
                                </div>
                            </div>
                        </div>
						
						 <div class="panel-body">
                                <div class="clearfix">


<form action="" method="post">
             	 <?php echo $this->form->csrf ?>
                               <table class="table table-striped table-hide table-hover space-mangead">                                   	
							   <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
						              <input type="hidden" name="pc_id" value="<?php echo $this->pc_id?>">
									  <tr><td><label> Name:</label></td>
									  <td><?php echo $this->form->name; ?></td></tr>
                                       <tr><td> <label > Email:</label></td>
									   <td><?php echo $this->form->email; ?></td></tr>
										<tr><td> <label >Comment:</label></td>
										<td><?php echo $this->form->comment; ?></td></tr>
										 <tr><td>&nbsp;</td><td>
                                        <button type="submit" class="btn btn-primary">Save</button>
										</td></tr>   
                                        </table>
            </form>
			
			
			</div>

                                </div>
				 		
                        <a href="#">
                            <div class="panel-footer">
                                
								 </a>
                            </div>
                       
                    </div>
                </div>
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>