<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.com/2008/fbml">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $this->escape($this->title); ?></title>

    <!-- Bootstrap -->
    <link href="<?php echo $this->baseUrl(); ?>/css/default/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="<?php echo $this->baseUrl(); ?>/css/default/site.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl(); ?>/css/default/normal.css" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/default/animation.css">   
     <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->    
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="<?php echo $this->baseUrl(); ?>/js/default/jquery/1.11.3/jquery.min.js"></script>-->
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/jquery-1.10.2.min.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/js/default/modernizr.js"></script>
  <script src="<?php echo $this->baseUrl(); ?>/js/default/animation.js"></script>


        
    </head>
  <body>
  <?php echo $this->render("header.phtml"); ?>

        <div class="container"><!--main container start -->
    <?php echo $this->layout()->content; ?>
     </div> <!--main container end-->

    <?php echo $this->render("footer.phtml"); ?>
  
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo $this->baseUrl(); ?>/js/default/bootstrap.min.js"></script>

<script>
$(function(){
//alert("Jquery is working");

});
</script>

  </body>
</html>