  <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
  					 <li>
                         <a href="<?php echo $this->baseUrl(); ?>/admin/index"><i class="fa fa-tachometer"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post"><i class="fa fa-file-o fa-fw"> </i> New Post</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->baseUrl(); ?>/admin/page/new-page"><i class="fa fa-file-o fa-fw"></i> New Page</a>
                        </li>
                         <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo3"><i class="fa fa-file-o fa-fw"></i> CMS Lists<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo3" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/posts/index"> Posts</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index">Pages</a>
                            </li>
                            </ul>
                         </li>
                          <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo4"><i class="fa fa-comments-o fa-fw"></i> Comments<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo4" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/post-comments/index"> Posts</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/comments/index">Pages</a>
                            </li>
                            </ul>
                         </li>
                         <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo5"><i class="fa fa-home fa-fw"></i> Blocks<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo5" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks"> Text Blocks</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks">Image Blocks</a>
                            </li>
                            </ul>
                         </li>
                         <li>
                         <a href="javascript:;" data-toggle="collapse" data-target="#demo6"><i class="fa fa-share fa-fw"></i> Social<i class="fa fa-fw fa-caret-down"></i></a>
                         <ul id="demo6" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/social"> Sharing</a>
                            </li>
                            <li>
                                <a href="#">Aggregation</a>
                            </li>
                            </ul>
                          </li>

                         <li>
                         <a href="javascript:;" data-toggle="collapse" data-target="#demo7"><i class="fa fa-picture-o fa-fw"></i> Photo Gallery<i class="fa fa-fw fa-caret-down"></i></a>
                         <ul id="demo7" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/new-photo"> Add Photo</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/gallery">Gallery List</a>
                            </li>
                             <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/photo-categories/new">Add Category</a>
                            </li>
                             <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/photo-categories"> Categories List</a>
                            </li>
                            </ul>
                          </li>
                
	                         <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/index"><i class="fa fa-file-o fa-fw"> </i> Sliders</a>
                          </li>
                      <!--testimonial-->
                        <li>
                         <a href="javascript:;" data-toggle="collapse" data-target="#demo8"><i class="fa fa-picture-o fa-fw"></i> Testimonial<i class="fa fa-fw fa-caret-down"></i></a>
                         <ul id="demo8" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/testimonial/new"> New</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/testimonial">List</a>
                            </li>
                             
                         </ul>
                        </li>
                        <!--testimonial end-->

                        <!--testimonial-->
                        <li>
                         <a href="javascript:;" data-toggle="collapse" data-target="#demo9"><i class="fa fa-picture-o fa-fw"></i> Videos<i class="fa fa-fw fa-caret-down"></i></a>
                         <ul id="demo9" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/videos/new"> New</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/videos">List</a>
                            </li>
                             
                         </ul>
                        </li>
                        <!--testimonial end-->

                        <!--setting-->
                       <li>
                        <a href="<?php echo $this->baseUrl(); ?>/admin/setting/index"><i class="fa fa-cogs"> </i> Setting</a>
                        </li>
                        <!--setting end-->
<li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/gd/index"> <i class="fa fa-gears"> </i> Google Analytics</a>
                                
                        </li>
                      </ul>

   </div>