  <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo1"><i class="fa fa-picture-o fa-fw"></i> Strip Banners<i class="fa fa-fw fa-caret-down"></i> </a>
                        <ul id="demo1" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/Strip-Banner/new-strip-banner"><i class="fa fa-picture-o fa-fw"></i>  New Strip Banner</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/Strip-Banner/strip-banner-list"><i class="fa fa-file-image-o"></i> Strip Banner List</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo10"><i class="fa fa-file-text-o fa-fw"></i> Text Block <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo10" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/Text-Blocks/text-blocks-list"><i class="fa fa-file-text-o"></i> Text Block List</a>
                            </li>
                        </ul>
                                </div>