 <li>
                            <a class="active" href="<?php echo $this->baseUrl(); ?>/admin/index/"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>

                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/blog/posts-list"><i class="fa fa-users fa-fw"></i> Blog Posts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/blog/new-post">New Blog Post</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/blog/posts-list">Blog Posts List</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/post-comments/post-list">Comments</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-users fa-fw"></i> Pages<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/page/new-page">Add New Page</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/page/lists">Page List</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/comments/page-list">Comments</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>


                         <li>
                        <a href="#"><i class="fa fa-video-camera fa-fw"></i> Videos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/index/new-videolink"><i class="fa fa-video-camera fa-fw"></i> New Video<span class=""></span></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/index/video-list"><i class="fa fa-video-camera fa-fw"></i> Videos List<span class=""></span></a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>


                        <li>
                         <a href="#"><i class="fa fa-comments fa-fw"></i> Testimonials<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                   <a href="<?php echo $this->baseUrl(); ?>/admin/index/new-testimonial"><i class="fa fa-comments fa-fw"></i> New Testimonial<span class=""></span></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/index/testimonial-list"><i class="fa fa-comments"></i> Testimonials List<span class=""></span></a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>


                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/index/home-page-text"><i class="fa fa-file-text-o fa-fw"></i> Home Page Text<span class=""></span></a>
                        </li>

                        <li>
                         <a href="#"><i class="fa fa-picture-o fa-fw"></i> Banners<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                   <a href="<?php echo $this->baseUrl(); ?>/admin/banner/new-banner"><i class="fa fa-picture-o fa-fw"></i> New Banner<span class=""></span></a>
                                </li>

                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/banner/banner-list"><i class="fa fa-file-image-o"></i> Banner List<span class=""></span></a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                          <a href="#"><i class="fa fa-picture-o fa-fw"></i> Strip Banners<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                   <a href="<?php echo $this->baseUrl(); ?>/admin/Strip-Banner/new-strip-banner"><i class="fa fa-picture-o fa-fw"></i> New Strip Banner<span class=""></span></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/Strip-Banner/strip-banner-list"><i class="fa fa-file-image-o"></i> Strip Banner List<span class=""></span></a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>

                         <a href="<?php echo $this->baseUrl(); ?>/admin/Social-Link/edit-social-links"><i class="fa fa-share fa-fw"></i> Social Media Links<span class="fa arrow"></span></a>

                       </li>






                        <li>
                            <a href="#"><i class="fa fa-users fa-fw"></i> Categories<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/categories/new-category"> Add New Category</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/categories/list">List</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>


                        <li>
                            <a href="#"><i class="fa fa-users fa-fw"></i> Users<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/user/new"> Add New</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/user/list">List</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="#"><i class="glyphicon glyphicon-comment"></i> Settings<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/gd/index"> Google Analytics</a>
                                </li>

                            </ul>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-image"></i> Gallery<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/new-photo"> Add New Image</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/photo-list">Gallery List</a>
                                </li>

                            </ul>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/index/update-urls"><i class="fa fa-link fa-fw"></i> Update Urls</a>
                        </li>

                        <!--<li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/user/update-password/id/<?php echo $this->user_id ?>"><i class="fa fa-user fa-fw"></i> Users<span class=""></span></a>
                            <ul>
                            <li>
                            <a href="<?php echo $this->baseUrl(); ?>/admin/user/update-password/id/<?php echo $this->user_id ?>"><i class="fa fa-user fa-fw"></i> Users<span class=""></span></a>
                            </li>
                            </ul>
                         </li>-->
                         <!-- / User -->
