  <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
  					<li>
                        <a href="<?php echo $this->baseUrl(); ?>/admin/posts/new-post"><i class="fa fa-file-o fa-fw"> </i> New Post</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->baseUrl(); ?>/admin/page/new-page"><i class="fa fa-file-o fa-fw"></i> New Page</a>
                        </li>
                         <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo3"><i class="fa fa-file-o fa-fw"></i> CMS Lists<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo3" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/posts/posts-list"> Posts</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/page/lists">Pages</a>
                            </li>
                            </ul>
                         </li>
                          <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo4"><i class="fa fa-comments-o fa-fw"></i> Comments<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo4" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/post-comments/post-list"> Posts</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/comments/page-list">Pages</a>
                            </li>
                            </ul>
                         </li>
                         <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo5"><i class="fa fa-home fa-fw"></i> Landing Page<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo5" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks"> Text Blocks</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks">Image Blocks</a>
                            </li>
                            </ul>
                         </li>
                         <li>
                         <a href="javascript:;" data-toggle="collapse" data-target="#demo6"><i class="fa fa-share fa-fw"></i> Social<i class="fa fa-fw fa-caret-down"></i></a>
                         <ul id="demo6" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/social"> Sharing</a>
                            </li>
                            <li>
                                <a href="#">Aggregation</a>
                            </li>
                            </ul>
                          </li>
                    </ul>
   </div>