
<div class="row">
<div class="col-md-10 col-md-offset-1">
<center>
<h1 style="color:#AF075C"> Certified GSC Experts </h1>
<hr/>
<h2 style="color:#f26aa3">Tell us about your experience!</h2>
<h3 style="color: #56c145"><?php echo $this->expert_name;?></h3>
<h4 style="color:#f26aa3"><?php echo $this->role;?></h4>
<div  style="position: relative; width: 250px; height: 250px; margin:auto">
<img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/expert/originals/<?php echo $this->image;?>" style="margin:auto;max-width:100%; max-height: 100%"/>
</div>
</center>
</div>
 <div class="col-md-11 set-head">
 <a href="<?php echo $this->baseUrl(); ?>/index/expert-detail/id/<?php echo $this->expert_id;?>"><i class="fa fa-backward"></i> Go back to expert details</a>
		   
			<form action="<?php echo $this->baseUrl()?>/index/add-review/id/<?php echo $this->expert_id?>" method="post">
             	 <?php echo $this->form->csrf ?>
                                       	<table class="table table-striped table-bordered table-hover space-mangead">                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										
                                       <?php echo $this->form->first_name; ?>
                                        <?php echo $this->form->last_name; ?>
                                         <?php echo $this->form->email; ?>
                                         <?php echo $this->form->message; ?>
										 <tr><td><label>Expert Rating:<br/>Please select a value of 1-5 stars for the Expert's level in the categories to the right.</label></td>
										 <td><div id="consis"><label>Consistency:</label></div><div id="know"><label>Knowledge:</label></div><div id="app"><label>Approach:</label></div><div id="comm"><label>Communication:</label></div></td></tr>
                                     <input type="hidden" name="expert_id" value="<?php echo $this->expert_id;?>"/>
									 <input type="hidden" name="consistency" id="consistency" value="0"/>
									 <input type="hidden" name="knowledge" id="knowledge" value="0"/>
									 <input type="hidden" name="approach" id="approach" value="0"/>
									 <input type="hidden" name="communication" id="communication" value="0"/>
                                    <tr><td>&nbsp;</td><td>
                                        <?php echo $this->form->submit?>
										</td></tr>   
                                        </table>
                
            </form>
 
 </div><!--col-10 end--> 

</div><!--row end-->
<script src="<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/vendor/jquery.js"></script><script src="<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/lib/jquery.raty.js"></script>
<script src="<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/javascripts/labs.js" type="text/javascript"></script>
<script type="text/javascript">
$('#consis').raty({starOff : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-off.png', 
starOn  : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-on.png', click: function(score, evt) {
    $('#consistency').val(score);
  } });
$('#know').raty({starOff : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-off.png', 
starOn  : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-on.png', click: function(score, evt) {
    $('#knowledge').val(score);
  }});
$('#app').raty({starOff : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-off.png', 
starOn  : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-on.png', click: function(score, evt) {
    $('#approach').val(score); 
  }});
$('#comm').raty({
starOff : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-off.png', 
starOn  : '<?php echo $this->baseUrl()?>/js/raty-2.7.0/raty-2.7.0/demo/images/star-on.png', click: function(score, evt) {
    $('#communication').val(score); 
  }});

</script>
<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
			
	
 </script>