<!--</div>  



<!--bhootstrap sheets-->
<!--
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">

<!--bhootstrap sheets end-->


<!--

<style>
.row {
    margin-left: 0 !important ;
    margin-right: 0 !important ;
}

.client{
	background-color:#F00;
}
	
.client h3 {
    color: rgb(255, 255, 255);
    font-size: 25px;
	margin:27px 0 20px;
}
.form-group {
    margin: 0px 0;
}	

.set-btn {
    background-color: rgb(0, 0, 0) !important;
    border: 1px solid rgb(0, 0, 0) !important;
    border-radius: 0 !important;
    color: rgb(255, 255, 255) !important;
    margin: 21px 0 0px !important;
}
	
	.row {
    margin-left: -15px;
    margin-right: 0 !important;
}

input {
    border: 0 solid rgb(255, 255, 255) !important;
    border-radius: 0 !important;
    height: 40px !important;
}

.carousel-caption {
    left: 10%;
    padding-bottom: 30px;
    text-align: left;
    top: 30%;
}
   
   
.carousel-caption h2 {
    line-height: 5px;
}   
   

/*/

.carousel-control.left {
    background-image:none !important;
    background-repeat: repeat-x;
}

.carousel-control.right {
    background-image: none;
    background-repeat: repeat-x;
}

 */

   
</style>


<div class="row">

<div id="myCarousel" class="carousel slide" data-ride="carousel"> 
  <!-- Indicators -->
 <!-- 
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>-->
  <!--
  <div class="carousel-inner">
    <div class="item active"> 
	
	<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" style="width:100%;height:550px"/>
    		
					<div class="container">				 
				
						<div class="carousel-caption">
							<h2>a hub for</h2>
							<h1><span style="color:#de2f2f">ASPRING AND </span></h1>
							<h2>active entrepreneurs... </h2>
								</div>
						
								</div>
						
								</div>
    <div class="item"> 	<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" style="width:100%;height:550px"/>
      <div class="container">
        <div class="carousel-caption">
        <h2>a hub for</h2>
        <h1><span style="color:#de2f2f">ASPRING AND </span></h1>
       <h2>active entrepreneurs... </h2>
         </div> 
      </div>
    </div>
    <div class="item"> 	<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" style="width:100%;height:550px"/>
      <div class="container">
        <div class="carousel-caption">
          <h2>a hub for</h2>
      <h1><span style="color:#de2f2f">ASPRING AND </span></h1>
      <h2>active entrepreneurs... </h2>
         
        </div> 
      </div>
    </div> 
  </div>
  </div>
  
  
</div>

  
  
  
 <a class="left carousel-control" href="#myCarousel" data-slide="prev">
  <span class="glyphicon glyphicon-chevron-left"></span></a> 
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
  <span class="glyphicon glyphicon-chevron-right"></span></a> </div>
  
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	 
	 
	 
<!--bootstrap slider end -->
	 
	 
	 




<!--
	 
	  
     <div class="row client">
      <div class="container">
      <div class="col-md-3">
      <h3>Client's E-mail Portal</h3>
       </div>
       
   
      <form>
  <div class="col-md-3">      
  <div class="form-group">
    <label for="exampleInputEmail1"></label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Name">
  </div>
  </div>
  
  <div class="col-md-3">
  <div class="form-group">
    <label for="exampleInputEmail1"></label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  </div>
  
  <div class="col-md-3">
  <button type="submit" class="btn btn-default set-btn">Submit</button>

      </div>
   </form>   
      </div>
      </div>
      
	  
	  								<!-- slider section-->
 <!--<script src="<?php echo $this->baseUrl();?>/js/nhot/jquery.js"></script>-->
<!--
 <body>
 <div class="row">
 <header id="myCarousel" class="carousel slide">
        <!-- Indicators --><!--
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
		<!--
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" alt="slide1">
				</div>
                <div class="carousel-caption">
                    <h2>Caption 1</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" alt="slide1">
				</div>
                <div class="carousel-caption">
                    <h2>Caption 2</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" alt="slide1">
				</div>
                <div class="carousel-caption">
                    <h2>Caption 3</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
		<!--
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>
	 <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>
	</div>
</body>
   