
  <div class="exp service-parlex">
    <div class="exp-back">
      <div class="w-container">
        <div id="who-v-animation">
        <div class="wrap">
          <div class="w-row exp-des">
            <div class="w-col w-col-6 exp-col1">
              <div class="col1-div">
                <div class="experinc-box">
                <h3 class="experinc-box-h3"><?php echo $this->text_block[1]['tb_name']?></h3>
                <p><?php echo $this->text_block[1]['tb_text']?></p>
                <div class="buttons">
                <div class="btn-ex-one">
                  <a class="ex-btn" href="#">Read More</a>
                </div>
                <div class="btn-ex-two">
                  <a class="ex-btn-two" href="#">Buy Now!</a>
                </div>
              </div>
              </div>
              </div>
            </div>
            <div class="w-col w-col-6 exp-col2">
              <div class="col2-div">
                <a href="<?php echo $this->image_block[3]['link']?>"><img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[3]['block']?>"></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
