 
 <section class="service-parlex" id="service">
    <section class="parlex-back">
      <div class="w-container">
        <div class="wrap">
          <div class="service-combo">
            <div class="services">
              <h1 class="service-heading"><?php echo $this->text_block[3]['tb_name']?></h1>
              <!--<div class="services-text">WHAT WE DO?</div>-->
              <div class="sepreater service"></div>
            </div>
            <div class="services-text"><?php echo $this->text_block[3]['tb_text']?></div>
            <div class="w-row">
              <div class="w-col w-col-3 services-column">
                <a href="<?php echo $this->image_block[4]['link']?>">
                <div class="service-icon">
                  <img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[4]['block']?>">
                </div>
                <h4 class="service-head"> <?php echo $this->image_block[4]['name']?></h4>
                </a>
              </div>
              <div class="w-col w-col-3">
               <a href="<?php echo $this->image_block[5]['link']?>">
                <div class="service-icon">
                  <img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[5]['block']?>">
                </div>
                <h4 class="service-head"> <?php echo $this->image_block[5]['name']?></h4>
                </a>
              </div>
              <div class="w-col w-col-3">
                <div class="service-icon">
                 <a href="<?php echo $this->image_block[6]['link']?>">
                  <img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[6]['block']?>">
                </div>
                <h4 class="service-head"> <?php echo $this->image_block[6]['name']?></h4>
                </a>
              </div>
              <div class="w-col w-col-3">
                <div class="service-icon">
                 <a href="<?php echo $this->image_block[7]['link']?>">
                  <img src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[7]['block']?>">
                </div>
                <h4 class="service-head"> <?php echo $this->image_block[7]['name']?></h4>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </section>