<div id="about" class="about-parlex">
    <section class="parlex7-back">
      <div class="w-container">
        <div id="about-animation" class="expandUp">
        <div class="wrap">
          <div class="about">
            <h1 class="about-heading"><?php echo $this->text_block[0]['tb_name']?></h1>
            <div class="sepreater"></div>
          </div>
          <p class="about-des"> <?php echo $this->text_block[0]['tb_text']?></p>
        
      <div class="row-fluid set-blog-img">
			 <div class="col-md-4">
		     <a href="<?php echo $this->image_block[0]['link']?>"><img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[0]['block']?>" class="about-img"></a>
       </div>
       <div class="col-md-4">
		     <a href="<?php echo $this->image_block[1]['link']?>"><img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[1]['block']?>" class="about-img"></a>	
			 </div>
			 <div class="col-md-4">
		     <a href="<?php echo $this->image_block[2]['link']?>"><img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/user/image-blocks/<?php echo $this->image_block[2]['block']?>" class="about-img"></a>
       </div>
			</div>
		
		  </div>
      </div>
      </div>
    </section>
  </div>
