
<div class="team-parlex" id="team">
    <div class="parlex5-back">
      <div class="w-container">
        <div class="wrap">
          <div class="team">
            <h1 class="team">TEAM</h1>
            <div class="sepreater team-sep"></div>
          </div>
          <div class="team-text">
            <p class="team-text-para">We are Elegance. We offer creative solutions for every web-based project you can think of.&nbsp;
              <br>We take pride in our work and everything we create is executed with precision and love.</p>
          </div>
          <div class="w-row team-member">
            <div class="w-col w-col-4">
              <div class="team-section">
                <div class="team-image">
                  <img class="team-img" src="images/default/team/image1.png" alt="52dd1e57e64ce6cb200004f3_image1.png">
                </div>
                <div class="team-des">
                  <h4 class="team-name">JANE ANISTON</h4>
                  <div class="team-name-des">Creative Director</div>
                </div>
                <div class="team-social">
                  <div class="w-clearfix social-section">
                    <a href="https://www.facebook.com/"><img class="social" src="images/default/social/Facebook.png" alt="52dd249c929b601f5400054c_Facebook.png"></a>
                    <a href="https://www.twitter.com/"><img class="social" src="images/default/social/Twitter.png" alt="52dd24f2929b601f54000551_Twitter.png"></a>
                    <a href="https://www.linkedin.com/"><img class="social" src="images/default/social/Linkedin.png" alt="52dd2672e64ce6cb2000053a_Linkedin.png"></a>
                    <a href="https://plus.google.com/"><img class="social" src="images/default/social/Google-plus.png" alt="52dd26a55b54031d540005af_Google-plus.png"></a>
                    <a href="https://www.rss.com/"><img class="social" src="images/default/social/RSS.png" alt="52dd26d25b54031d540005b4_RSS.png"></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="w-col w-col-4">
              <div class="team-section">
                <div class="team-image">
                  <img class="team-img" src="images/default/team/image2.png" alt="52dd1edfe64ce6cb200004fb_image2.png">
                </div>
                <div class="team-des">
                  <h4 class="team-name">JOHN DOE</h4>
                  <div class="team-name-des">Lead Developer</div>
                </div>
                <div class="team-social">
                  <div class="w-clearfix social-section">
                    <a href="https://www.facebook.com/"><img class="social" src="images/default/social/Facebook.png" alt="52dd249c929b601f5400054c_Facebook.png"></a>
                    <a href="https://www.twitter.com/"><img class="social" src="images/default/social/Twitter.png" alt="52dd24f2929b601f54000551_Twitter.png"></a>
                    <a href="https://www.linkedin.com/"><img class="social" src="images/default/social/Linkedin.png" alt="52dd2672e64ce6cb2000053a_Linkedin.png"></a>
                    <a href="https://plus.google.com/"><img class="social" src="images/default/social/Google-plus.png" alt="52dd26a55b54031d540005af_Google-plus.png"></a>
                    <a href="https://www.rss.com/"><img class="social" src="images/default/social/RSS.png" alt="52dd26d25b54031d540005b4_RSS.png"></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="w-col w-col-4">
              <div class="team-section">
                <div class="team-image">
                  <img class="team-img" src="images/default/team/image3.png" alt="52dd1efcad165eca20000539_image3.png">
                </div>
                <div class="team-des">
                  <h4 class="team-name">TANE NISTON</h4>
                  <div class="team-name-des">Graphic Designer</div>
                </div>
                <div class="team-social">
                  <div class="w-clearfix social-section">
                    <a href="https://www.facebook.com/"><img class="social" src="images/default/social/Facebook.png" alt="52dd249c929b601f5400054c_Facebook.png"></a>
                    <a href="https://www.twitter.com/"><img class="social" src="images/default/social/Twitter.png" alt="52dd24f2929b601f54000551_Twitter.png"></a>
                    <a href="https://www.linkedin.com/"><img class="social" src="images/default/social/Linkedin.png" alt="52dd2672e64ce6cb2000053a_Linkedin.png"></a>
                    <a href="https://plus.google.com/"><img class="social" src="images/default/social/Google-plus.png" alt="52dd26a55b54031d540005af_Google-plus.png"></a>
                    <a href="https://www.rss.com/"><img class="social" src="images/default/social/RSS.png" alt="52dd26d25b54031d540005b4_RSS.png"></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!--///////////////////////////////////////////////////////
       // End Team section 
       //////////////////////////////////////////////////////////-->

<!--///////////////////////////////////////////////////////
       // Clients section 
       //////////////////////////////////////////////////////////-->

  <div class="clients-parlex">
    <div class="parlex6-back">
      <div class="w-container">
        <div class="wrap-client">
          <div class="clients-sub">
            <div id="clients">
        <div class="clients-wrap">
          <ul id="clients-list" class="clearfix">
            <li><img src="images/default/clients/client-logo1.png" alt="logo"></li>
            <li><img src="images/default/clients/client-logo2.png" alt="logo"></li>
            <li><img src="images/default/clients/client-logo3.png" alt="logo"></li>
            <li><img src="images/default/clients/client-logo4.png" alt="logo"></li>
            <li><img src="images/default/clients/client-logo5.png" alt="logo"></li>
            <li><img src="images/default/clients/client-logo6.png" alt="logo"></li>
          </ul>
        </div><!-- @end .clients-wrap -->
      </div><!-- @end #clients -->
          </div>
        </div>
      </div>
    </div>
  </div>