
<div class="portfolio-parlex" id="portfolio">
    <div class="parlex3-back">
      <div class="w-container">
        <div class="wrap">
          <div class="portfolio">
            <h1 class="portfolio-heading"><?php echo $this->text_block[9]['tb_name']?></h1>
            
            <div class="sepreater"></div>
          </div>
          <p class="porfolio-paragraph"><?php echo $this->text_block[9]['tb_text']?></p>
            <div class="container demo-1">
      <ul class="grid cs-style-1">
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[0]['photo_name']?>" alt="img01">
            <figcaption style="display: none;">
              <h3>Camera</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[1]['photo_name']?>" alt="img02">
            <figcaption style="display: none;">
              <h3>Music</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[2]['photo_name']?>" alt="img04">
            <figcaption style="display: none;">
              <h3>Settings</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption >
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[3]['photo_name']?>" alt="img05">
            <figcaption style="display: none;">
              <h3>Safari</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[4]['photo_name']?>" alt="img03">
            <figcaption style="display: none;">
              <h3>Phone</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[5]['photo_name']?>" alt="img06">
            <figcaption style="display: none;">
              <h3>Game Center</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[6]['photo_name']?>" alt="img06">
            <figcaption style="display: none;">
              <h3>Game Center</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[7]['photo_name']?>" alt="img06">
            <figcaption style="display: none;">
              <h3>Game Center</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure>
            <img class="portfolio-images" src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->gallery[8]['photo_name']?>" alt="img06">
            <figcaption style="display: none;">
              <h3>Game Center</h3>
              <span>Jacob Cummings</span>
              <a href="#">Take a look</a>
            </figcaption>
          </figure>
        </li>
      </ul>
    </div><!-- /container -->
        </div>
      </div>
    </div>
  </div>