
<div class="process-parlex">
    <div class="parlex2-back">
      <div class="w-container">
        <div class="wrap">
          <div class="process">
            <h1 class="our-process-heading"><?php echo $this->text_block[4]['tb_name']?></h1>
            <div class="sepreater"></div>
          </div>
          <div class="process-text">
            <div class="process-text"><?php echo $this->text_block[4]['tb_text']?></div>
            <div class="w-row">
              <div class="w-col w-col-3">
                <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
                   <a href="#set-1" class="hi-icon hi-icon-lockeds">Security</a>
                </div>
                <h4 class="our-process-sys"><?php echo $this->text_block[5]['tb_name']?></h4>
                <p class="process-paragraph"><?php echo $this->text_block[5]['tb_text']?></p>
              </div>
              <div class="w-col w-col-3">
                <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
          <a href="#set-1" class="hi-icon hi-icon-mobiles">Mobile</a>
        </div>
                <h4 class="our-process-sys"><?php echo $this->text_block[6]['tb_name']?></h4>
                <p class="process-paragraph"><?php echo $this->text_block[6]['tb_text']?></p>
              </div>
              <div class="w-col w-col-3">
                <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
          <a href="#set-1" class="hi-icon hi-icon-screens">Desktop</a>
        </div>
                <h4 class="our-process-sys"><?php echo $this->text_block[7]['tb_name']?></h4>
                <p class="process-paragraph"><?php echo $this->text_block[7]['tb_text']?></p>
              </div>
              <div class="w-col w-col-3">
                <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
          <a href="#set-1" class="hi-icon hi-icon-earths">Partners</a>
        </div>
                <h4 class="our-process-sys"><?php echo $this->text_block[8]['tb_name']?></h4>
                <p class="process-paragraph"><?php echo $this->text_block[8]['tb_text']?></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>