 
 <div class="call-to-action">
    <div class="call-to-back">
      <div class="w-container">
        <div class="wrap">
          <div class="w-row call-row">
            <div class="w-col w-col-9 cal-col-1">
              <h3 class="call-to-h3"><?php echo $this->text_block[2]['tb_name']?></h3>
              <p><?php echo $this->text_block[2]['tb_text']?></p>
            </div>
            <div class="w-col w-col-3"><a class="call-to-butn" href="#">Buy Now!</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  
