
<!--

</div>

		<!--slider section-->
<!-- <div class="row">
 
 <header id="myCarousel" class="carousel slide">
				<!-- Indicators -->
   <!--     <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>-->
				<!-- Wrapper for slides -->
  <!--      <div class="carousel-inner">
            <div class="item active">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" alt="slide1">
				</div>
				<div class="container">
				
			
			  <div class="carousel-caption">
                    <h2>a hub for</h2>
					<h1><span style="color:#de2f2f">aspiring and</span></h1> 
					<h1>active entrepreneurs...</h1> 
                </div> 
				
				
				</div>
				</div>
            <div class="item">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" alt="slide1">
				</div>
              <div class="row">
				<div class="container">
			  <div class="col-md-5">
			  <div class="carousel-caption">
                    <h2>a hub for</h2>
					<h1><span style="color:#de2f2f">aspiring and</span></h1> 
					<h1>active entrepreneurs...</h1> 
                </div>
				</div>
				</div>
				</div>
            </div>
            <div class="item">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png" alt="slide1">
				</div>
              <div class="row">
				<div class="container">
			  <div class="col-md-5">
			  <div class="carousel-caption">
                    <h2>a hub for</h2>
					<h1><span style="color:#de2f2f">aspiring and</span></h1> 
					<h1>active entrepreneurs...</h1> 
                </div>
				</div>
				</div>
				</div>
            </div>
        </div>
					<!-- Controls -->
 <!--       <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>
	 <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>
	</div>

<!--form section-->
<!--	 <div class="row client">
      <div class="container">
      <div class="col-md-3">
      <h3>Client's E-mail Portal</h3>
       </div>
        <form>
  <div class="col-md-3">      
  <div class="form-group">
    <label for="exampleInputEmail1"></label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Name">
  </div>
  </div>
  <div class="col-md-3">
  <div class="form-group">
    <label for="exampleInputEmail1"></label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  </div>
  <div class="col-md-3">
  <button type="submit" class="btn btn-default set-btn">Submit</button>
    </div>
   </form>   
      </div>
      </div>
				<!--end form section-->
   
<!--
<div class="row">
		<div class="container">
		<div class="col-md-8 col-md-offset-2 set-contact-text">
		<h4>To contact Brendon or his staff directly, use the following information. - See more at: http://brendonburchard.com/contact/#sthash.UackqORF.dpuf</h4>
		<h3>General Inquiries:</h3>
<h4>info@burchardgroup.com</h4>
<h3>Mailing Address:</h3>
<h4>The Burchard Group</h4>
<h4>PO Box 5368</h4>
<h4>Portland, OR 97228</h4>
<h3>Brendon Burchard Interviews and Speaking inquiries</h3>
<h4>Molly Curran</h4>
<h4>molly@expertsacademy.com</h4>

<h3>Bulk Order Requests:</h4>
<h4>To order Brendon Burchard books visit Amazon.com or your local bookseller. For orders of 500 copies or more, email us at info@burchardgroup.com. </h4><h3>Bulk discounts on orders less than 500 copies are not available.</h3>
  

 




		</div>	
		</div>
		</div>--> 