 <style type="text/css">
</style>
 <!-- Image Blocks Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Image Blocks</h2>
            </div>
            
            <?php foreach($this->image as $item): ?>
            <?php if ($this->v<6){$this->v++; ?>
            <div class="col-md-4 col-sm-6">
                <a href="<?php echo $item['link']?>" target="_blank">
                    <h4><?php echo $item['name']?></h4>
                    <img class="img-responsive image-row1 img-hover" src="<?php echo $this->baseUrl(); ?>/images/user/image-blocks/500X500/<?php echo $item['block']?>" alt="image-block">
                </a>
            </div>
            <?php } ?>
            <?php endforeach ?>
        </div>
        <!-- /.row -->
