
</div>
 <body>
		<!--slider section-->
 <div class="row">
 
 <header id="myCarousel" class="carousel slide">
				<!-- Indicators -->
   <!--     <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>-->
				<!-- Wrapper for slides -->
        <!-- <div class="carousel-inner">
            <div class="item active">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png"/>
				</div>
				<div class="container">
				<div class="carousel-caption">
                 <h1>The </h1>
				 <h1><span style="color:#de2f2f">Pit Stop </span>for</h1> 
				<h1>Entrepreneurs</h1> 
                 </div>
			    </div>
				</div>
            <div class="item">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png"/>
				</div>
         
		
			  <div class="carousel-caption">
				  <h1>The </h1>
				 <h1><span style="color:#de2f2f">Pit Stop </span>for</h1> 
				<h1>Entrepreneurs</h1> 
                </div>
			
            </div>
            <div class="item">
                <div class="fill">
				<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/slide1.png"/>
				</div>
    			  <div class="carousel-caption">
                     <h1>The </h1>
				 <h1><span style="color:#de2f2f">Pit Stop </span>for</h1> 
				<h1>Entrepreneurs</h1> 
				</div>  
				 
            </div>
        </div> -->
					<!-- Controls -->
        <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a> -->
	
		
		 <div class="fill">
		<a href="<?php echo  $this->banner->target_url;?>">	
		<!-- img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/banners/1600/banner2.png"/ -->
		<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/banners/original/<?php echo  $this->banner->banner_img;?>" alt="Banner Image"/>
		
				</a>
				</div>
	
	</header>
	<!-- <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script> -->
	</div>

			<!--end sliders section-->
						<!--form section-->
	 <div class="row client">
      <div class="container">
        <div class="col-md-12">
			<center>
		<a href="<?php echo  $this->strip->target_url;?>">
		<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/strip-banner-images/original/<?php echo  $this->strip->banner_img;?>" alt="Strip Image"/>
		
		</a>
			</center>
		</div>

		</div>
	  
	  
	  
	  
	  <?php /*
	  <div class="container">
      <div class="col-md-4">
		<center>
	 <h3>  Don't wait, let's connect!  </h3>
		</center>
	 </div>
        <form>
  <div class="col-md-3">      
  <div class="form-group">
    <label for="exampleInputEmail1"></label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Name">
  </div>
  </div>
  <div class="col-md-3">
  <div class="form-group">
    <label for="exampleInputEmail1"></label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  </div>
  <div class="col-md-1">
  <center>
  <button type="submit" class="btn btn-default set-btn">Submit</button>
    </center>
	</div>
   </form>   
      </div>
	  */ ?>
      </div>
				<!--end form section-->
   
					<!--content section-->
<div class="row">
<div class="container">
<div class="col-md-12 content">
<!-- h1>About Todd Johnson</h1 -->
<h3></h3> <p><h4>
<?php echo $this->row_text ; ?>
</h4>
</p>
  
</div>
</div>
</div>
<!--end content section-->
<!--work section-->
							
<div class="row work">  
<div class="col-md-12">
<h1>Work With Me</h1>
</div>
</div>
<div class="row work">
<div class="container">

<a href="<?php echo $this->baseUrl();?>/cms/mastermind/">
<div class="col-md-4 master-border master">
<center>
<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/MIND.png" alt="Master Mind">
</center>
<h3><span style="color:#f4b3b3">Mastermind </span></h3>
</div>
</a>

<a href="<?php echo $this->baseUrl();?>/cms/private-coaching/">
<div class="col-md-4 master-border master">
<center>
<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/PRIVATE.png" alt="Private Coaching">
</center>
<h3><span style="color:#f4b3b3">Private Coaching</span> </h3>
</div></a>

<a href="<?php echo $this->baseUrl();?>/cms/millionair-mindset/">
<div class="col-md-4 master">
<center>
<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/MILION.png" alt="Millionaire">
</center>
<h3><span style="color:#f4b3b3">Academy</span> </h3>
</div></a>





<!--
<a href="<?php echo $this->baseUrl();?>/cms/millionair-mindset">
<div class="col-md-3 col-md-offset-1">
<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/MILION.png">
<h3><span style="color:#f4b3b3">Millionaire Mindset</span></h3>
</div>
</a>
-->

</div>
</div>
</div>
								<!--work section end-->
								
								  <!--blog section-->
								  
<div class="container" id='vc'>
<div class="row video-box">
<div class="col-md-7 blogs table-responsive">
<h3>Video Blogs</h3>
<?php if (count($this->paginator)){ ?>
<table class="table">
<?php foreach ($this->paginator as $item): ?>
<tr><td width="30%" style="align: center;">
<a href="<?php echo $this->baseUrl(); ?>/index/videos/id/<?php echo $item['v_id']?>">
<div class="responsive-image image-water-mark">
<img src="<?php echo $this->baseUrl();?>/images/video/200X200/<?php echo $item['video_img']?>" alt="Vedio Image 1"/>
<h6 class="set-water-mark">
<span>
<div style="position: relative; width: 100px; height: 100px">
<img style="max-width:100%; max-height: 100%" src="<?php echo $this->baseUrl();?>/images/video-paly1.png" alt="Video Image 2"/>
</div>
<span>
</h6>
</div>
</a>
</td>
<td width="70%" style="align: top;"> 

<h5><span style="color:#806f58"><?php echo $item['title']?></span></h5>
<!--<h5><span style="color:#806f58">Charges: </span>3 Simple Tips to Getting the Family to Eat Healthy</h5>-->
<div class="set-description">
<?php echo $item['short_description']?><!--Snippet description of case Introduction and results-->
<!-- h4>Video Link</h4 -->
</div>
<br/>
<br />
<div>
<!--
<div class="seprator"><img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/seprator.jpg" /></div>

<a href="<?php echo $this->baseUrl(); ?>/index/videos/id/<?php echo $item['v_id']?>"><h5><span style="color:#806f58">Click here to watch!</span></h5></a>
 </div>
-->
 </td>
</tr>

<?php endforeach; ?>
</table>

  		<?php }else{ ?>

		<?php } ?>
	


<div class="bottom-blog">
<div class="set-paginatr">
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'video_pagination_control.phtml'); ?>
</div>
</div>
</div>
								<!--end blog section-->

								<!--testimonial-section-->

<div class="col-md-4 col-md-offset-1 set-testimonial-text">
<div class="row">
<div class="col-md-12">

<h2><span style="color:#f63234">Testimonials</span></h2>
<?php foreach($this->list as $item): ?>
        
					   <?php if ($this->i<=1){$this->i++; ?>
                  
<blockquote><?php echo $item['short_description']?></blockquote>
<span style="color:#969696"> </h4><span class="quote"></span></span> 
</div>
</div>
<div class="row">
<div class="col-md-4 set-testimonial-text-btn">
<div style="position: responsive; width: 100px; height: 100px">
<img class="img-responsive img-circle set-testimonial-image" src="<?php echo $this->baseUrl(); ?>/images/testimonial-images/200X200/<?php echo $item['image1']?>" alt="Testimonial Image"/>
</div>
</div>

<div class="col-md-7">		
<h4 class="testimonial-heading-set"><span style="color:#f63234"><?php echo $item['first_name']?> &nbsp;<?php echo $item['last_name']?></style></h4>
 	</div>
</div>

 <?php }?>
		 
        <?php endforeach; ?>

<div class="row">
<div class="col-md-11 pull-right">

 <a class="btn btn-default set-testimonial-btn" href="<?php echo $this->baseUrl();?>/index/more-testimonials">More Testimonials</a>

</div> 
</div>

 
</div> 
</div>
<!--end testimonial-section-->

   

</body>