<?php echo $this->render("/index/slider1.phtml");  ?>
<?php echo $this->render("/index/block1.phtml");  ?>
<?php echo $this->render("/index/block2.phtml");  ?>
<?php echo $this->render("/index/block3.phtml");  ?> 
<?php echo $this->render("/index/block4.phtml");  ?>
<?php echo $this->render("/index/block5.phtml");  ?>
<?php echo $this->render("/index/block6.phtml");  ?>
<?php echo $this->render("/index/block7.phtml");  ?>
<?php echo $this->render("/index/block8.phtml");  ?>

     