
</div>
<div class="container">
<h2 class="set-testimonials-heading">Our Testimonials</h2>
<div class="row set-testimonial-row">

<?php
$counter = 0;
if (count($this->paginator)){ 
foreach ($this->paginator as $item): ?>
<div class="col-md-4">   
<div class="row">
<div class="col-md-12">
<blockquote><?php echo $item['short_description']?></blockquote>
<span class="quote"></span>
</div>
</div>
<div class="row">
  <div class="col-md-6" style="position: responsive; width: 100px; height: 100px">
        <img class="img-responsive img-circle set-testimonial-image" src="<?php echo $this->baseUrl(); ?>/images/testimonial-images/200X200/<?php echo $item['image1']?>"/>
    </div>
<div class="col-md-6">	
	<h4 class="testimonial-heading-set"><span style="color:#f63234"><?php echo $item['first_name']?> &nbsp;<?php echo $item['last_name']?></style></h4>
</div>
	</div>	
</div>

<?php 
if($counter > 2){
echo "</div><div class='row set-testimonial-row'>";
$counter = 0;
}
$counter++;
endforeach; ?>
<?php } ?>
</div><!-- /.row -->
<div class="row">
<div class="col-md-4 col-md-offset-4"><center>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'video_pagination_control.phtml'); ?>
</center>
</div>
</div>
<div class="row">
<div class="col-md-4 col-md-offset-4">
&nbsp;
</div>
</div>
</div><!-- /.container -->