
<div><h1> SITE MAP</h1> </div>
<div class="container">
<div class="row">
<div class="col-md-12">

<div class="col-md-4">
<h3 class="nav-links">Home</h3>
<a href="<? $this->baseUrl();?>/colinkr/index">HOME</a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
</div>

<div class="col-md-4">
<h3 class="nav-links">Blog</h3>
<a href="<? $this->baseUrl();?>/colinkr/blog/posts">Posts</a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
</div>

<div class="col-md-4">
<h3 class="nav-links">Page</h3>
<a href="<? $this->baseUrl();?>/colinkr/pages/page">Pages</a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
</div>

</div>
</div>
<div class="row">
<div class="col-md-12">

<div class="col-md-4">
<h3 class="nav-links">About</h3>
<a href="<? $this->baseUrl();?>/colinkr/cms/about">About Us</a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
<a href="#"> &nbsp </a>
</div>

</div>
</div>
</div>