

<!--
<div class="row">
<div class="col-md-2">
<div class="gulity-image">
<a href="#"><img src="<?php echo $this->baseUrl();?>/images/nhot-image/blog2.jpg"/></a>
</div>
</div>
<div class="col-md-10">
<div class="gulity">
<h5><span style="color:#806f58">Charges: </span>3 Simple Tips to Getting the Family to Eat Healthy</h5>
<span class="set-description"><p>Snippet description of case Introduction and results</p></span>
<h4>goes here.</h4>
<div class="seprator"><img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/seprator.jpg" /></div>
<a href="#"><h5><span style="color:#806f58">Learn How We Won this Legal fight.</span></h5></a>
</div>
</div>
</div>
<div class="border-bottom"></div>


<div class="row">
<div class="col-md-2">
<div class="gulity-image">
<a href="#"><img class="set-blog-image"src="<?php echo $this->baseUrl();?>/images/nhot-image/blog3.jpg"/></a>
</div>
</div>
<div class="col-md-10">
<div class="gulity">
<h5><span style="color:#806f58">Charges: </span>3 Simple Tips to Getting the Family to Eat Healthy</h5>
<span class="set-description"><p>Snippet description of case Introduction and results</p></span>
<h4>goes here.</h4>
<div class="seprator"><img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/seprator.jpg" /></div>
<a href="#"><h5><span style="color:#806f58">Learn How We Won this Legal fight.</span></h5></a>
</div>
</div>
</div>
-->


<!--testimonial-->




