  <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Text Blocks
                </h1>
            </div>
            <!--<?php echo "I like " . $this->results[5
            ]['tb_text'] . ", " . $this->results[1]['tb_name'] . " and " . $this->results[2]['tb_name'] . ".";?>-->
            <?php foreach($this->list as $item): ?>
            <?php if ($this->i<6){$this->i++; ?>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> <?php echo $item['tb_name']?></h4>
                    </div>
                    <div class="panel-body">
                        <p><?php echo $item['tb_text']?></p>   
                    </div>
                </div>
            </div> 
            <?php } ?>
    <?php endforeach ?>
        </div>
        <!-- /.row -->
