
<!--

<div class="row work">
<div class="col-md-12">
<h1>Work With Me </h1>
</div>
</div>
<div class="row work">
<div class="container">
<a href="#">
<div class="col-md-3 col-md-offset-1 master-border">
<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/MIND.png">
<h3><span style="color:#f4b3b3">Mastermind </span></h3>
</div></a>
<a href="#">
<div class="col-md-3 col-md-offset-1 master-border">
<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/PRIVATE.png">
<h3><span style="color:#f4b3b3">Private Coaching</span> </h3>
</div></a>
<a href="#">
<div class="col-md-3 col-md-offset-1">
<img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/MILION.png">
<h3><span style="color:#f4b3b3">Millionaire Mindset</span></h3>
</div>
</a>
</div>
</div>



</div>-->