<!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
                 	
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-bullhorn fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Manage Expert Password</div>
                            
                                </div>
                            </div>
                        </div>
                            <div class="panel-body">
                               <?php echo $this->render("/xp/xp-menu.phtml"); ?>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  <div id="basic_info">
                                    <form class="form-horizontal" action="<?php echo $this->baseUrl();?>/admin/xp/change-password" method="post">
									<?php echo $this->form->csrf ?>
                                       	<table class="table-responsive table table-striped table-bordered table-hover space-mangead">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										<tr ><td colspan="2"><strong><a href="#">Change Password</a></strong></td></tr> 
         								<?php echo $this->form->pwd_current;?>
										<?php echo $this->form->pwd;?>
										<?php echo $this->form->pwd_confirm;?>
										<input type="hidden" name="expert_id" value="<?php echo $this->expert_id;?>"/>
										<tr><td>&nbsp;</td><td><input type="submit" class="btn btn-lg btn-primary float-right" value="Update Password"/>
										
                                        </table>
                                   </form>
	                            </div>
                            </div>
                      
                    </div>
                       <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



 <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
			
	
 </script>