<style>/*
.table-responsive {
    overflow-x: auto;
    overflow-y: hidden;
    width: 100% !important;
}*/
</style>

<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                         <div class="row" style="height:50px; padding:0; margin:0"><!-- row 1-->
                 <div class="col-xs-3">
                 <!--	<table class="table">
                    <tr><td> <a href="#"> <i class="fa fa-list  alert-warning"> List</i></a></td>
                    <td>  <a href="#"> <i class="fa fa-plus alert-warning"> New</i></a></td>
                    </tr>
                    </table>-->
                 </div>
                 </div><!-- ./ row 1-->
                 
                 
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-1">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                              <!--  <div class="col-xs-6"> 
                                <form action="<?php echo $this->baseUrl(); ?>/admin/index/all-comments" action="get">
                                <div class="input-group custom-search-form col-xs-6 text-right space-serch" style="padding-top:20px">
                                <input type="text" name="query_string" id="query_string" class="form-control" placeholder="Name or Email......">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            </form>
                                </div>-->
                                <div class="col-xs-3 pull-right ">
                                    <div class="huge"> Comments 
                        </div>
                                </div>
                            </div>
                        </div>
                   
                        
                             <div class="panel-body">
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                               <div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="table table-bordered">
														<thead>
                                                        
															<tr>
																<th style="text-align:center;">Expert Name</th>
																<th style="text-align:center;">From </br> Name & Email</th>
                                                              <!--  <th>Email</th>-->
                                                                <th style="text-align:center;">Comments</th>
																<th style="text-align:center;">Status</th>
														      <!--  <th>Consistency</th>
																<th>Knowledge</th>
																<th>Approach</th>
																<th>Communication</th>-->
															 	</tr>
														</thead>		
														<tbody>
                                          <tr id="msg"><td colspan="6"><?php echo $this->msg ?></td></tr>
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td style="text-align:center;">
															<?php echo $item['expert_FName']?> <?php echo $item['expert_LName']?>
															</td>
                                                            <td style="text-align:center;">
															<?php echo $item['date']?></br></br>
															<?php echo $item['first_name']?>  <?php echo $item['last_name']?></br></br>
															<?php echo $item['email']?>
															</td>
                                                         <!--   <td>
															<?php echo $item['email']?>
															</td>-->
                                                            
															<td>
															<p>
															<?php echo $item['comments']?>
															</p>
															
                                                           <p>
														  <table class="table-bordered" style="width: 100%;">
														  <tr>
															<td style="text-align:center;"> Consistency:</td>
															<td style="text-align:center;">
															<?php if($item['consistency']==1)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star1-02.png" width="100"/><?php }
															 elseif($item['consistency']==2)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 2-02.png" width="100"/><?php }
															 elseif($item['consistency']==3)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 3-02.png" width="100"/><?php }
															 elseif($item['consistency']==4)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 4-02.png" width="100"/><?php }
															 elseif($item['consistency']==5)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 5-02.png" width="100"/><?php }?>
															</td>
															
                                                           
															<td style="text-align:center;">Knowledge:</td>
															<td style="text-align:center;">
															<?php if($item['knowledge']==1)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star1-02.png" width="100"/><?php }
															 elseif($item['knowledge']==2)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 2-02.png" width="100"/><?php }
															 elseif($item['knowledge']==3)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 3-02.png" width="100"/><?php }
															 elseif($item['knowledge']==4)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 4-02.png" width="100"/><?php }
															 elseif($item['knowledge']==5)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 5-02.png" width="100"/><?php }?>
															</td>
															</tr>
															<tr>
                                                            <td style="text-align:center;">Approach:</td>
															<td style="text-align:center;">
															<?php if($item['approach']==1)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star1-02.png" width="100"/><?php }
															 elseif($item['approach']==2)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 2-02.png" width="100"/><?php }
															 elseif($item['approach']==3)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 3-02.png" width="100"/><?php }
															 elseif($item['approach']==4)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 4-02.png" width="100"/><?php }
															 elseif($item['approach']==5)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 5-02.png" width="100"/><?php }?>
															</td>
															
															
                                                            <td style="text-align:center;">Communication:</td>
															<td style="text-align:center;">
															<?php if($item['communication']==1)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star1-02.png" width="100"/><?php }
															 elseif($item['communication']==2)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 2-02.png" width="100"/><?php }
															 elseif($item['communication']==3)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 3-02.png" width="100"/><?php }
															 elseif($item['communication']==4)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 4-02.png" width="100"/><?php }
															 elseif($item['communication']==5)
															{?><img class="img-responsive" src="<?php echo $this->baseUrl()?>/images/logo/star 5-02.png" width="100"/><?php }?>
															</td> 
															</tr>
															</table>
															</p>
															</td>
															
														<?php if ($item['is_comment']==0){ ?>
														<td style="text-align:center;"><a class="btn btn-sm btn-danger float-right" onclick="return updateComments(<?php echo $item['comment_id'] ?> )" href="#">Pending</a></td>
														<?php }  
														 else{ ?>
														<td style="text-align:center;"><a class="btn btn-sm btn-success float-right" href="#">Approved</a></td>
														<?php } ?>
													
													</tr>
															<?php endforeach; ?>
															<tr><td colspan='9' style="text-align:center;">
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="7"><h4>There are no Comments List created! Please create one</h4></td></tr>
															<?php } ?>
														</tbody>

														</table>
                                                        <!-- / table responsive --> 
                                                        </div>
												</div>

                               
                            </div>    
                         <a href="#">
                            <div class="panel-footer">
                          </div>   
                        </a>       
                            
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 
 function updateComments(id)
 {
	 var r = confirm("Are you sure to Approved this Comment? " );
 if (r == true) {
 window.location.assign("<?php echo $this->baseUrl(); ?>/admin/xp/update-comment/id/" + id);    
 } else {
 return false;
 } 
 }
 </script>