<style>
.set-gallery-images {
}

table {
	table-layout: fixed; 
}

@media only screen and (min-width: 496px) and (max-width: 980px)
{
	.set-gallery-images {
   margin-top:10%;  
}
	
.table-responsive {
    border: 1px solid #ddd;
    margin-bottom: 15px;
    overflow-x: auto;
    overflow-y: hidden;
    width: 100%;
}
table {
	table-layout: auto; 
}
}

</style>
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
                 	
                 </div>  
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-bullhorn fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Manage Expert Gallery Images</div>
                            
                                </div>
                            </div>
                        </div>
                            <div class="panel-body">
                               <?php echo $this->render("/xp/xp-menu.phtml"); ?>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  <div id="basic_info">
                                    <form class="form-horizontal" action="<?php echo $this->baseUrl();?>/admin/xp/gallery-images" enctype="multipart/form-data" method="post">
									 	<div class="table-responsive set-gallery-images">
										<table class="table table-striped table-bordered table-hover">
                                    	<tr id='msg'><td colspan='3'><?php echo $this->msg ?></td></tr>
										<tr ><td colspan="3"><strong><a href="#">Expert Gallery Images</a></strong></td></tr> 
										<tr><td><input id="fileupload" type="file" name="image1"></td>
										<td><input id="fileupload" type="file" name="image2"></td>
										<td><input id="fileupload" type="file" name="image3"></td></tr>
										<tr><td><? if($this->expert_id>0 && $this->image1 != null){?><img style="height:90px;" src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image1;?>" alt=""/><a href="#" onclick="deleteExpert(<?php echo $this->expert_id?>,'<?php echo $this->image1?>',1)" class="btn btn-sm btn-danger float-right" style="float:right;">Delete</a><?php }?></td>
										<td><? if($this->expert_id>0 && $this->image2 != null){?><img style="height:90px;" src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image2;?>" alt=""/><a href="#" onclick="deleteExpert(<?php echo $this->expert_id?>,'<?php echo $this->image2?>',2)" class="btn btn-sm btn-danger float-right" style="float:right;">Delete</a><?php }?></td>
										<td><? if($this->expert_id>0 && $this->image3 != null){?><img style="height:90px;" src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image3;?>" alt=""/><a href="#" onclick="deleteExpert(<?php echo $this->expert_id?>,'<?php echo $this->image3?>',3)" class="btn btn-sm btn-danger float-right" style="float:right;">Delete</a><?php }?></td></tr>
										<tr><td><input id="fileupload" type="file" name="image4"></td>
										<td><input id="fileupload" type="file" name="image5"></td>
										<td><input id="fileupload" type="file" name="image6"></td></tr> 
										<tr><td><? if($this->expert_id>0 && $this->image4 != null){?><img style="height:90px;" src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image4;?>" alt=""/><a href="#" onclick="deleteExpert(<?php echo $this->expert_id?>,'<?php echo $this->image4?>',4)" class="btn btn-sm btn-danger float-right" style="float:right;">Delete</a><?php }?></td>
										<td><? if($this->expert_id>0 && $this->image5 != null){?><img style="height:90px;" src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image5;?>" alt=""/><a href="#" onclick="deleteExpert(<?php echo $this->expert_id?>,'<?php echo $this->image5?>',5)" class="btn btn-sm btn-danger float-right" style="float:right;">Delete</a><?php }?></td>
										<td><? if($this->expert_id>0 && $this->image6 != null){?><img style="height:90px;" src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image6;?>" alt=""/><a href="#" onclick="deleteExpert(<?php echo $this->expert_id?>,'<?php echo $this->image6?>',6)" class="btn btn-sm btn-danger float-right" style="float:right;">Delete</a><?php }?></td></tr>
                                     <input type="hidden" name="expert_id" value="<?php echo $this->expert_id;?>"/>
                                    <tr><td colspan="3">
                                        <input type="submit" value="Save" name="submit" class="btn btn-lg btn-primary float-right"/>
										</td></tr>   
                                        </table>
										</div>
                                   </form>
	                            </div>
                            </div>
                      
                    </div>
                       <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
}

function deleteExpert(id,name,num)
 {
	 var r = confirm("Are you sure to delete this image? " );
 if (r == true) {
 window.location.assign("<?php echo $this->baseUrl()?>/admin/xp/delete-gallery-image/?id="+id+"&name="+name+"&num="+num);    
 } else {
 return false;
 } 
 }
</script>