<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/tinymce/js/tinymce/tinymce.min.js"></script>
<script>tinymce.init({
 selector:'textarea',
      theme: "modern",
	  theme_xenforo_fonts : "Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;Courier New=courier new,courier;Georgia=georgia,palatino;Helvetica=helvetica;Impact=impact,chicago;Tahoma=tahoma,arial,helvetica,sans-serif;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva",
 plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor"
    ],
    toolbar1: "insertfile undo redo | styleselect | fontselect | fontsizeselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
  });
</script>
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
                 	
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-bullhorn fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Manage Expert Basic Info.</div>
                            
                                </div>
                            </div>
                        </div>
                            <div class="panel-body">
                               <?php echo $this->render("/xp/xp-menu.phtml"); ?>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  <div id="basic_info">
                                    <form class="form-horizontal" action="<?php echo $this->baseUrl();?>/admin/xp/new-expert/id/<?php echo $this->expert_id;?>" method="post" enctype="multipart/form-data" >
									<?php echo $this->form->csrf ?>
                                       	<table class="table-responsive table table-striped table-bordered table-hover space-mangead">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										<tr ><td colspan="2"><strong><a href="#">Basic Information</a></strong></td></tr> 
         												
                                       <?php //echo $this->form->first_name; ?>
                                        <?php //echo $this->form->last_name; ?>
                                         <?php //echo $this->form->email; ?>
                                         <?php //echo $this->form->city; ?>
                                         <?php //echo $this->form->state; ?>
                                         <?php //echo $this->form->zip_code; ?>
                                         <?php //echo $this->form->address; ?>
                                         <?php echo $this->form->short_bio; ?>
                                         <?php //echo $this->form->is_certified; ?>
										 <?php //echo $this->form->certification;?>
                                         <?php //echo $this->form->is_featured; ?>
										<!--
										 <tr><td><Label>Role</Label></td><td><?php //echo $this->form->role;?></td></tr> -->
                                         <tr><td><Label>Main Photo</Label></td><td><?php echo $this->form->image1;?><? if($this->expert_id>0 && $this->image1 != null){?><img src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image1;?>" alt="" style="float:right;"/><?php }?></td></tr>
                                         <tr><td><Label>Before Photo</Label></td><td><?php echo $this->form->image2;?><? if($this->expert_id>0 && $this->image2 != null){?><img src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image2;?>" alt="" style="float:right;"/><?php }?></td></tr>
                                         <tr><td><Label>After Photo</Label></td><td><?php echo $this->form->image3;?><? if($this->expert_id>0 && $this->image3 != null){?><img src="<?php echo $this->baseUrl()?>/images/expert/100X100/<?php echo $this->image3;?>" alt="" style="float:right;"/><?php }?></td></tr>
                                     <input type="hidden" name="expert_id" value="<?php echo $this->expert_id;?>"/>
                                    <tr><td>&nbsp;</td><td>
                                        <?php echo $this->form->submit?>
										</td></tr>   
                                        </table>
                                   </form>
	                            </div>
                            </div>
                      
                    </div>
                       <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



 <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
			
	
 </script>