  <span class="pull-left"><ul class="nav nav-tabs" role="tablist">
  <li <?php if(isset($this->basic)) echo "class = 'active'"; ?>><a href="<?php echo $this->baseUrl();?>/admin/xp/new-expert">Basics</a></li>
  <li <?php if(isset($this->social)) echo "class = 'active'"; ?>><a href="<?php echo $this->baseUrl();?>/admin/xp/social-media">Social Media</a></li>
  <li <?php if(isset($this->detail)) echo "class = 'active'"; ?>><a href="<?php echo $this->baseUrl();?>/admin/xp/bio-detail">Bio Detail</a></li>
  <li <?php if(isset($this->gallery)) echo "class = 'active'"; ?>><a href="<?php echo $this->baseUrl();?>/admin/xp/gallery-images">Gallery</a></li>
  <li <?php if(isset($this->password)) echo "class = 'active'"; ?>><a href="<?php echo $this->baseUrl();?>/admin/xp/change-password">Change Password</a></li> 
</ul></span>