<style>
.set-job{
	margin-top: 6%;
}
</style>
	 <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-9 col-md-16">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-3">
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-automobile fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit Category</div>
                            
                                </div>
                            </div>
                        </div>
                        
                            <div class="panel-body">
                                <!--<span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>-->
                                <div class="clearfix">
                                 
                                    <form class="form" action="<?php echo $this->form->action ?>" method="POST" >
                                       	<table class="table table-striped table-bordered table-hover set-job">
                                    	<tr id='msg'><td id='td_msg' colspan='2'><?php echo $this->msg ?></td></tr>
										
										<?php echo $this->form->category; ?>												
                                         	
                                                <tr><td>&nbsp;</td><td>
                                         <?php echo $this->form->submit; ?>
												</td></tr>
						
                                       
											</table>   
											</form>
	                             
                   
                                </div>
                            </div>
                       
                    </div>
                </div>
                </div>
                </div>
					
                </div>
         
        <!-- /#page-wrapper -->
<script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
		
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
		
 </script>

