<style type="text/css">
.border-red{
	border: 3px solid red;
}
.template{
	border: 2px solid #757575;
	padding: 10px;
	margin-top: 30px;
}
.block1{
	border: 2px solid #757575;
	padding: 30px;
}
.block2{
	border: 2px solid #757575;
	padding: 20px;
	margin-top: 30px;
}
.block3{
	border: 2px solid #757575;
	padding: 20px;
	margin-top: 30px;
}
.block4{
	border: 2px solid #757575;
	padding: 20px;
	margin-top: 30px;
}
.block5{
	border: 2px solid #757575;
	padding: 20px;
	margin-top: 30px;
}
.block6{
	border: 2px solid #757575;
	padding: 20px;
	margin-top: 30px;
}
.block7{
	border: 2px solid #757575;
	padding: 20px;
	margin-top: 30px;
}
	</style>


<div class="row">
 <div class="col-md-12">
  <div class="template">
  <div class="row">
   <div class="col-md-4">
    <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[0]['ib_id']?>">
     <div class="border-red" style="height:50px;">
    	<h3 style="text-align: center;">Logo (Image Block 1)</h3>
     </div>
    </a>
   </div>
   <div class="col-md-8">
   	<div class="meun" style="height:50px; border: 2px solid #757575;">
   		<h3 style="text-align: center;">Navigation Menu</h3>
   	</div>
   </div>
  </div><!--row1 end-->
  <div class="row">
   <div class="col-md-12">
    <a href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $this->slides[0]['slider_id']?>">
   	<div class="sliders border-red" style="height:200px; margin: 20px 0 20px 0;">
   		<h1 style="text-align: center;">Sliders Section</h1>
   	</div>
   	</a>
   </div>
  </div><!-- row2 end-->
  <!--block1 -->
  <div class="row">
  	<div class="col-md-12">
  	<h3 style="text-align: center;">Block 1</h3>
  	<div class="block1">
  	 <div class="row">
  	  <div class="col-md-12">
  	  	<a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[0]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 1</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div>	
  	 <div class="row">
  	 <!--first section image block-->
  	  <div class="col-md-4">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[1]['ib_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 2</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  
  	  <!--3rd section image block-->
  	   <div class="col-md-4">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[2]['ib_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 3</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  <!--3rd section image block-->
  	  <div class="col-md-4">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[3]['ib_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 4</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div><!--row end-->
  	 </div>
  	</div>
   </div><!--row 3 end-->
   <!-- blocl1 end-->
   <!-- block2 start-->
   <div class="row">
    <div class="col-md-12">
    <h3 style="text-align: center;">Block 2</h3>
     <div class="block2">
      <div class="row">
    	<div class="col-md-6">
    	<a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[1]['tb_id']?>">
   		 <div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		  <h3 style="text-align: center;">Text Block 2</h3>
  	  	 </div>
  	  	 </a>
   	    </div>
     	<div class="col-md-6">
     	<a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[4]['ib_id']?>">
   		 <div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		  <h3 style="text-align: center;">Image Block 5</h3>
  	  	 </div>
  	  	 </a>
   	    </div>
   	  </div>
   	 </div>
   	</div>
   </div><!--row4 end-->
   <!--block2 end-->
   <!--block 3 -->
   <div class="row">
    <div class="col-md-12">
    <h3 style="text-align: center;">Block 3</h3>
     <div class="block3">
      <div class="row">
    	<div class="col-md-12">
    	<a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[2]['tb_id']?>">
   		 <div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		  <h3 style="text-align: center;">Text Block 3</h3>
  	  	 </div>
  	  	 </a>
   	    </div>
   	  </div>
   	 </div>
   	</div>
   </div><!-- row5 end-->
   <!--block 3 end-->
   <!--block 4 -->
   <div class="row">
  	<div class="col-md-12">
  	<h3 style="text-align: center;">Block 4</h3>
  	<div class="block4">
  	 <div class="row">
  	  <div class="col-md-12">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[3]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 4</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div>	
  	 <div class="row">
  	 <!--first section image block-->
  	  <div class="col-md-3">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[5]['ib_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 6</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  
  	  <!--3rd section image block-->
  	   <div class="col-md-3">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[6]['ib_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 7</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  <!--3rd section image block-->
  	  <div class="col-md-3">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[7]['ib_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 8</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	   <!--4th section image block-->
  	  <div class="col-md-3">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[8]['ib_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 9</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div><!--row end-->
  	 </div>
  	</div>
   </div><!--row 6 end-->
   <!--block 4 end-->
   <!-- block 5 -->
   <div class="row">
  	<div class="col-md-12">
  	<h3 style="text-align: center;">Block 5</h3>
  	<div class="block5">
  	 <div class="row">
  	  <div class="col-md-12">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[4]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 5</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div>	
  	 <div class="row">
  	 <!--first section Text block-->
  	  <div class="col-md-3">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[5]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 6</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  
  	  <!--3rd section Text block-->
  	   <div class="col-md-3">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[6]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 7</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  <!--3rd section Text block-->
  	  <div class="col-md-3">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[7]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 8</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	   <!--4th section Text block-->
  	  <div class="col-md-3">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[8]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 9</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div><!--row end-->
  	 </div>
  	</div>
   </div><!--row 6 end-->
   <!-- block 5 end-->
   <!-- block6 -->
   <div class="row">
  	<div class="col-md-12">
  	<h3 style="text-align: center;">Block 6</h3>
  	<div class="block6">
  	 <div class="row">
  	  <div class="col-md-12">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[9]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 10</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div>	
  	 <div class="row">
  	 <!--first section Photo Gallery-->
  	  <div class="col-md-4">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[0]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 1</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  
  	  <!--3rd section Text block-->
  	   <div class="col-md-4">
  	    <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[1]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 2</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  <!--3rd section Text block-->
  	  <div class="col-md-4">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[2]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 3</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div><!--photo gallery row1 end-->
  	 <div class="row">
  	 <!--4th section Photo Gallery-->
  	  <div class="col-md-4">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[3]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 4</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  
  	  <!--5th section Text block-->
  	   <div class="col-md-4">
  	    <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[4]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 5</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  <!--6th section Text block-->
  	  <div class="col-md-4">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[5]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 6</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div><!--photo gallery row2 end-->
  	 	 <div class="row">
  	 <!--7th section Photo Gallery-->
  	  <div class="col-md-4">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[6]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 7</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  
  	  <!--8th section Text block-->
  	   <div class="col-md-4">
  	    <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[7]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 8</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  <!--9th section Text block-->
  	  <div class="col-md-4">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/gallery/edit-photo/id/<?php echo $this->gallery[8]['photo_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Photo 9</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div><!--photo gallery row3 end-->
  	 </div>
  	</div>
   </div><!--row 7 end-->
   <!-- block6 end-->
   <!-- block7 -->
    <div class="row">
  	<div class="col-md-12">
  	<h3 style="text-align: center;">Block 7</h3>
  	<div class="block7">
  	 <div class="row">
  	  <div class="col-md-12">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $this->text[10]['tb_id']?>">
  	  	<div class="border-red" style="height:100px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Text Block 11</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div>	
  	 <div class="row">
  	 <!--first section Text block-->
  	  <div class="col-md-4">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[9]['ib_id']?>">
  	  	<div class="border-red" style="height:200px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 10</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  
  	  <!--3rd section Text block-->
  	   <div class="col-md-4">
  	   <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[10]['ib_id']?>">
  	  	<div class="border-red" style="height:200px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 11</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	  <!--3rd section Text block-->
  	  <div class="col-md-4">
  	  <a href="<?php echo $this->baseUrl(); ?>/admin/image-blocks/edit/id/<?php echo $this->image[11]['ib_id']?>">
  	  	<div class="border-red" style="height:200px; margin-bottom:20px;">
  	  		<h3 style="text-align: center;">Image Block 12</h3>
  	  	</div>
  	  	</a>
  	  </div>
  	 </div><!--row end-->
  	 </div>
  	</div>
   </div><!--row 6 end-->
   <!-- block 7 end-->
  </div><!--template end-->
 </div><!--main col-md-12 end-->
</div><!--main row end-->