 <script src="<?php echo $this->baseUrl();?>/js/admin/ckeditor/ckeditor.js"></script>
<div class="row">
    <div class="col-lg-12">
        <a href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/index"> <i class="btn btn-md btn-primary">Text Blocks List</i></a>
    </div>
</div>
<br />
 <div class="row">
 <div class="col-md-12">
 <div class="page-title">Edit  <strong><?php echo $this->escape($this->block_name); ?></strong> Text Block</div>
</div><!-- /.col-md-12-->
</div><!-- /.row -->
<br />

 <div class="row">
 <div class="col-md-12">
 <div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
		<br />
        
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
<table class="table space-mangead">

<tr><td><strong>Text Block</strong></td></tr>
  <?php echo $this->form->tb_text; ?>
 <tr><td><strong>Text Block Name</strong></td></tr>
 <?php echo $this->form->tb_name; ?>
<tr><td > <?php echo $this->form->submit?></td></tr>
</table>
</form>
 </div><!-- /.col-md-12-->
</div><!-- /.row -->


 <script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('#msg').hide();

    <?php  } else{
    ?>
      $('#msg').show().delay(3000).hide('slow');

    <?php } ?>
       // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
               CKEDITOR.replace( 'editor1' );
 }
 </script>