<div class="row">
 <div class="col-md-12">
 <div class="page-title"><h1>Text Blocks List</h1></div>
 </div><!-- /.col-md-12-->
</div><!-- /.row -->
        
            <div class="row">
                         <div class="col-md-12">
                    
                                <div class="table-responsive">
                                                    <table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered  set-table" width="100%">
                                                        <thead>

                                                            <tr>
                                                            <th style="text-align:center;">Text Block No.</th>
                                                                <th style="text-align:center;">Text Block Name</th>
                                                                <th style="text-align:center;">Text</th>
                                                                <th style="text-align:center;">Edit </th>
                                                                <th style="text-align:center;">Location on Home Page </th>

                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                        <?php if (count($this->paginator)){ ?>

                                                        <?php foreach ($this->paginator as $item): ?>

                                                        <tr class="odd gradeX">
                                                        <td style="text-align:center;">
                                                            <?php echo $item['tb_id'] ?>
                                                            </td>

                                                        <td style="text-align:center;">
                                                            <?php echo $item['tb_name'] ?>
                                                            </td>
                                                        <td style="text-align:center;">
                                                        <?php echo $item['tb_text'] ?>

                                                        </td>

                                                        <td style="text-align:center;"><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $item['tb_id'] ?>">Edit</a></td>

                                                        <td>

                                                        </td>
                                                                </tr>
                                                            <?php endforeach; ?>
                                                            <tr><td colspan='9' style="text-align:center;">
                                                            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
                                                            </td>
                                                            </tr><?php } ?>
                                                        </tbody>

                                                        </table>
                                                        </div><!-- div responsive end-->
                        
                                </div>
                            <!-- /.col-md-12 -->
                    </div>
            <!-- /.row -->
