<div class="row">
	<div class="col-md-12">
		<div class="page-title">
			<strong>Text Blocks List</strong>
		</div>
	</div>
	<!-- /.col-md-12-->
</div><!-- /.row -->
        <br />
        
            <div class="row">
                         <div class="col-md-12">
                    
                                <div class="table-responsive">
                                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                                        <thead>

                                                            <tr>
                                                            <th style="text-align:center;">Text Block No.</th>
                                                                <th style="text-align:center;">Text Block Name</th>
                                                                <th style="text-align:center;">Text</th>
                                                                <th style="text-align:center;">Edit </th>
                                                                <th style="text-align:center;">Location on Home Page </th>

                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                        <?php if (count($this->data)){ 
                                                            foreach ($this->data as $item): ?>

                                                        <tr class="odd gradeX">
                                                        <td style="text-align:center;">
                                                            <?php echo $item['tb_id'] ?>
                                                            </td>

                                                        <td style="text-align:center;">
                                                            <?php echo $item['tb_name'] ?>
                                                            </td>
                                                        <td style="text-align:center;">
                                                        <?php echo $item['tb_text'] ?>

                                                        </td>

                                                        <td style="text-align:center;"><a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/text-blocks/edit-text-block/id/<?php echo $item['tb_id'] ?>">Edit</a></td>

                                                        <td>

                                                        </td>
                                                                </tr>
                                                            <?php endforeach;  } ?>
                                                        </tbody>

                                                        </table>
                                                        </div><!-- div responsive end-->
                        
                                </div>
                            <!-- /.col-md-12 -->
                    </div>
            <!-- /.row -->
<script type="text/javascript">
    $(function() { 
        
        $('#dataTables-example').dataTable();
    });
 
</script>