<style>
 .set-table{
 float:left;
}
</style>    
    <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-12 col-md-26">
                         
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i class="fa fa-comments fa-4x"></i>
                                </div>
								
						<div class="col-xs-7">
                             <form class="form-inline" action="<?php echo $this->baseUrl()?>/admin/comments/page-list" method="post">
								<div class="form-inline">
								<?php echo $this->form->search_type?><span class="input-group-button"><button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button></span>	
							</div>
							</form>
                          </div>
								
                                <div class="col-xs-10 text-right">
                                    <div class="huge">Comments List</div>
                            
                                </div>
                            </div>
                        </div>
						
						 <div class="panel-body">
                               <!-- <span class="pull-left">Use buttons for operations</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>-->
                                <div class="clearfix">
                                <div class="table-responsive">
													<table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered  set-table" width="100%">
														<thead>
														<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
															<tr>
																<th style="text-align:center;"> Page Title</th>
																<th style="text-align:center;">Name </th>
																<th style="text-align:center;">Email </th>
																<th style="text-align:center;">Comment </th>
																<th style="text-align:center;">Date </th>
																<th style="text-align:center;">Status </th>
																<th style="text-align:center;">Action</th>
																<th style="text-align:center;">Edit</th>
																<th style="text-align:center;">Delete</th>
                                                        	</tr>
														</thead>		
														<tbody> 
                                          
														<?php if (count($this->paginator)){ ?>
													
														<?php foreach ($this->paginator as $item): ?>
														<tr class="odd gradeX">
															<td style="text-align:center;"> <?php echo $item['title'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['name'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['email'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['comment'] ?> </td> 
															<td style="text-align:center;"> <?php echo $item['comment_date'] ?> </td> 
															<td style="text-align:center;">
															<?php if($item['status']== 1){?>
															Pending<?php }elseif($item['status']== 3){ ?>
															Rejected<?php }else{ ?>
															Approved<?php } ?>
															</td>
															<td style="text-align:center;">
															<?php if($item['status']== 1){?>
															<a class="btn btn-sm btn-primary" href="#" onclick="return confirmApprove(<?php echo $item['comment_id'] ?> )" >Approve</a><?php }elseif($item['status']== 3){ ?>
															<a class="btn btn-sm btn-primary" href="#" onclick="return confirmApprove(<?php echo $item['comment_id'] ?> )" >Approve</a> <?php }else{ ?>
															<a class="btn btn-sm btn-danger" href="#" onclick="return confirmReject(<?php echo $item['comment_id'] ?> )" >Reject</a> <?php } ?> </td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-warning" href="<?php echo $this->baseUrl(); ?>/admin/comments/edit-comment/id/<?php echo $item['comment_id'] ?>">Edit</a></td>
                                                            <td style="text-align:center;"><a class="btn btn-sm btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['comment_id'] ?> )" >Delete</a></td>
														</tr>  
															<?php endforeach; ?> 
															<tr><td colspan='9' style="text-align:center;">
															<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
															</td>
															</tr><?php }else{ ?>
											
															<tr><td colspan="9"><h4>There are no Categories List.</h4></td></tr>
															<?php } ?>
														</tbody>

						 								</table>
														</div><!-- div responsive end-->
												</div>

                                </div>
				 		
                        <a href="#">
                            <div class="panel-footer">
                                
								 </a>
                            </div>
                       
                    </div>
                </div>
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
 window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
 
 function confirmDelete(id){
	var r = confirm("Are you sure to Delete this Comment! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/comments/delete-comment/id/" + id);    
	} else {
	return false;
	}
	}
	
  function confirmApprove(id){
	var r = confirm("Are you sure to Approve this Comment! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/comments/approve-comment/id/" + id);    
	} else {
	return false;
	}
	}
	
  function confirmReject(id){
	var r = confirm("Are you sure to Reject this Comment! " );
	if (r == true) {
	window.location.assign("<?php echo $this->baseUrl(); ?>/admin/comments/reject-comment/id/" + id);    
	} else {
	return false;
	}
	}

 </script>