<style>
.space-mangead{
	margin-top: 3%;
}
</style>

<!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
            <div class="col-lg-12">
			<div class="col-lg-11">
            <div class="row" style="height:50px; padding:0; margin:0">
                 <div class="col-xs-5">
                 	
                 </div>
                 </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-graduation-cap fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit Gallery Image</div>
                            
                                </div>
                            </div>
                        </div>
                            <div class="panel-body">
                              
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                  <div id="basic_info">
                                    <form class="form-horizontal" action="<?php echo $this->baseUrl();?>/admin/gallery/edit-photo" method="post" enctype="multipart/form-data" >
								
                                       	<table class="table-responsive table table-striped table-bordered table-hover space-mangead">
                                    	<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										<!--<tr ><td colspan="2"><strong><a href="#">Basic Information</a></strong></td></tr>--> 
         							  
<tr><td><Label>Gallery Image:</Label></td><td><? if($this->photo_id>0 && $this->photo_name != null){?> <img src="<?php echo $this->baseUrl();?>/images/gallery-images/200X200/<?php echo $this->photo_name;?>" alt="" style="float:left; width:150px;"/> <?php }?></td></tr>									  
                                      
										  <tr><td><Label>Change Image:</Label></td><td><?php echo $this->form->photo_name;?></td></tr>
                                     <input type="hidden" name="photo_id" value="<?php echo $this->photo_id?>"/>
                                    <tr><td>&nbsp;</td><td>
                                        <?php echo $this->form->submit?>
										</td></tr>   
                                        </table>
                                   </form>
	                            </div>
                            </div>
                      
                    </div>
                       <a href="#">
                         <div class="panel-footer">
                         </div>
                        </a>
                </div>
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



 <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 }
			
	
 </script>