<script src="<?php echo $this->baseUrl();?>/js/admin/ckeditor/ckeditor.js"></script>
 <div class="row">
  <div class="col-md-12">
  <div class="page-title">Edit Photo</div>
  </div><!-- /.col-md-12-->
 </div><!-- /.row -->

 <div class="row">
   <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
  <div class="col-md-6">
    <table class="table space-mangead">
     <tr id='msg'><td ><?php echo $this->msg ?></td></tr>
      <tr><td><strong>Gallery Photo:</strong></td></tr><td>
      <img src="<?php echo $this->baseUrl();?>/images/user/photo_gallery/500X500/<?php echo $this->photo;?>" alt="gallery-image" style="float:left; width:300px"/></td>
      <tr><td><strong>Change Image:</strong>  <?php echo $this->form->photo_name; ?></td></tr>
  </table>
</div>
 <div class="col-md-6">
    <table class="table space-mangead">
      <tr><td><strong>Description:</strong></td></tr>
      <?php echo $this->form->description; ?>
      <tr><td><strong>Photo Link:</strong></td></tr>
      <?php echo $this->form->link; ?>
      <tr><td><strong>Photo Caption:</strong></td></tr>
      <?php echo $this->form->caption; ?>
      <tr><td><strong>Photo Category:</strong></td></tr>
      <tr><td><strong>Select Category:</strong></td></tr>
      <?php echo $this->form->category;?>
  
      <tr><td > <?php echo $this->form->submit?></td></tr>
     </table>
    </form>
  </div><!-- /.col-md-6-->
 </div><!-- /.row -->

<script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('tr#msg').hide();

    <?php  } else{
    ?>
      $('tr#msg').show().delay(3000).hide('slow');

    <?php } ?>
         // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
               CKEDITOR.replace( 'editor1' );
 }
 </script>