 <div class="row">
  <div class="col-md-12">
  <div class="page-title">Add Photo Gallery </div>
  </div><!-- /.col-md-12-->
 </div><!-- /.row -->

            <div class="row">
            <div class="col-lg-12">
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                    <table class="table space-mangead">
                        <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                         <tr><td><strong>Add Photo:</strong></td></tr><td>
                         <?php echo $this->form->photo_name;?>	
                         <tr><td><strong>Add Photo:</strong></td></tr><td>
                         <?php echo $this->form->photo_name;?>  
                         <tr><td><strong>Add Photo:</strong></td></tr><td>
                         <?php echo $this->form->photo_name;?>  						    
                            <?php echo $this->form->submit?>
                     </table>
                 </form>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>

<script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('tr#msg').hide();

    <?php  } else{
    ?>
      $('tr#msg').show().delay(3000).hide('slow');

    <?php } ?>
 }
 </script>