
<div class="row-fluid footer">
<div class="container">

<div class="col-md-3 copywrite">
<h5>Copyright © 2015 - nHotPursuit</h5>
<h5 style="color: #FFF">Website Design & developed by </br>nhotpursuit.com  </h5>
 
</div> 
<div class="col-md-6 footer-nav">

<div class="row footer-contect">
<div class="col-md-8 col-md-offset-2 set-footer-content-row">
<a href="<?php echo $this->baseUrl(); ?>/cms/privacypolicy" style="color: #FFF">Privacy Policy</a><seprator>|</seprator>
<a href="<?php echo $this->baseUrl(); ?>/cms/terms-of-use" style="color: #FFF">Terms of Use</a> <seprator>|</seprator>
<a href="<?php echo $this->baseUrl(); ?>/cms/disclaimer" style="color: #FFF">Disclaimer</a> 
</div>
</div>
</div>

<div class="col-md-3 footer-contect">
<h5>Toll-Free: (866) 874-7100</h5>
<h5>Email: info@nHotPursuit.com</h5>
<h5>455 Massachusetts Ave</br>
Suite #322
Washington, DC 20001</h5>
</div>
</div>
</div>

</body>