
<!-- dropdown menu script-->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript">

			function DropDown(el) {
				this.dd = el;
				this.initEvents();
			}
			DropDown.prototype = {
				initEvents : function() {
					var obj = this;

					obj.dd.on('click', function(event){
						$(this).toggleClass('active');
						event.stopPropagation();
					});	
				}
			}

			$(function() {

				var dd = new DropDown( $('#dd') );

				$(document).click(function() {
					// all dropdowns
					$('.wrapper-dropdown-5').removeClass('active');
				});

			});
			
			

		</script>
<!--end dropdown menu script-->

  <div class="container"> 
     <div class="col-md-12">  
     <div class="social-1 pull-right">
          <ul class="social-icons">   
														 <?php 
																if(strlen($this->links->facebook) > 6) { ?>
															   <li><a target="_blank" href="<?php echo  $this->links->facebook;?>"><img src="<?php echo $this->baseUrl();?>/images/nhot-image/facebok.png"></a></li>
															   <?php
																}else{
																	?>
																<li><img src="<?php echo $this->baseUrl();?>/images/nhot-image/facebok.png"></li>
																										   
																<?php 	
																} 
																
																if(strlen($this->links->linkedin) > 6) { ?>
															  <li><a target="_blank" href="<?php echo  $this->links->linkedin;?>"><img src="<?php echo $this->baseUrl();?>/images/nhot-image/in.png"></a></li>
															   <?php
																}else{
																	?>
																<li><img src="<?php echo $this->baseUrl();?>/images/nhot-image/in.png"></li>
																										   
																<?php 	
																} 
																
																if(strlen($this->links->twitter) > 6) { ?>
															 <li><a target="_blank" href="<?php echo  $this->links->twitter;?>"><img src="<?php echo $this->baseUrl();?>/images/nhot-image/DOT.png"></a></li>
															   <?php
																}else{
																	?>
																<li><img src="<?php echo $this->baseUrl();?>/images/nhot-image/DOT.png"></li>
																										   
																<?php 	
																}
																
																if(strlen($this->links->youtube) > 6) { ?>
															 <li><a target="_blank" href="<?php echo  $this->links->youtube;?>"><img src="<?php echo $this->baseUrl();?>/images/nhot-image/email.png"></a></li>
															   <?php
																}else{
																	?>
																<li><img src="<?php echo $this->baseUrl();?>/images/nhot-image/email.png"></li>
																										   
																<?php 	
																}if(strlen($this->links->instagram) > 6) { ?>
															 <li><a target="_blank" href="<?php echo  $this->links->instagram;?>"><img src="<?php echo $this->baseUrl();?>/images/nhot-image/instagram.png"></a></li>
															   <?php
																}else{
																	?>
																<li><img src="<?php echo $this->baseUrl();?>/images/nhot-image/instagram.png"></li>
																										   
																<?php 	
																}
																/*
																if(strlen($this->links->google_plus) > 6) { ?>
															 <li><a target="_blank" href="<?php echo  $this->links->google_plus;?>"><img src="<?php echo $this->baseUrl();?>/images/nhot-image/gplus.png"></a></li>
															   <?php
																}else{
																	?>
																<li><img src="<?php echo $this->baseUrl();?>/images/nhot-image/gplus.png"></li>
																										   
																<?php 	
																
																}
																
																if(strlen($this->links->tumblr) > 6) { ?>
															 <li><a target="_blank" href="<?php echo  $this->links->tumblr;?>"><img class="set-tumblr" src="<?php echo $this->baseUrl();?>/images/nhot-image/tumblr.png"></a></li>
															   <?php
																}else{
																	?>
																<li><img class="set-tumblr" src="<?php echo $this->baseUrl();?>/images/nhot-image/tumblr.png"></li>
																										   
																<?php 	
																}
																*/
																?> 
																
         														
		   </ul>
     </div>
   </div>

   
   </div>
 <nav class="navbar navbar-default" role="navigation"> 
        <div class="container"> 
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                    <span class="icon-bar"></span>
                </button>
			<a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/index"><img class="img-responsive" src="<?php echo $this->baseUrl();?>/images/nhot-image/logo.png"/></a>
            </div>  
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
					
               <a href="<?php echo $this->baseUrl();?>/index" 
						<?php 
						if($_SERVER['REQUEST_URI'] == '/index') echo 'class="active"'; 
						?>
						>Home 
						</a>
                    </li>
					
					<li><a href="<?php echo $this->baseUrl();?>/blog">Blog</a> </li>
				    <li><a href="<?php echo $this->baseUrl();?>/pages/page">Page</a> </li>
				    <li><a href="<?php echo $this->baseUrl();?>/index/gallery">Gallery</a> </li>
                    <li>
                        <a href="<?php echo $this->baseUrl();?>/cms/about/">About</a>
                    </li> 
					<!--drop down mene-->
					<!--<li>
					<div id="bb" class="wrapper-dropdown-5" tabindex="1">
					<a class="set-drop-link" href="#">Work With Me</a>
						<ul class="dropdown">
							<!--<li><a href="http://nhotpursuit.com/cms/mastermind/"><i class="icon-user"></i>Mastermind</a></li>
							<li><a href="http://nhotpursuit.com/cms/private-coaching/"><i class="icon-cog"></i>Private Coaching</a></li>
							<li><a href="http://nhotpursuit.com/cms/millionair-mindset/"><i class="icon-remove"></i>Millionaire Mindset</a></li>
						</ul>
					</div>
	
					</li>	-->	
							
					<!--<li>
                        <a href="<?php echo $this->baseUrl();?>/cms/about/">About</a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->baseUrl();?>/index/videos" 
						<?php 
						if($_SERVER['REQUEST_URI'] == '/index/videos') echo 'class="active"'; 
						?>>Video</a> 
                    </li>-->
					
					<!--<li>
                        <div id="dd" class="wrapper-dropdown-5" tabindex="1">
					<a class="set-drop-link" href="#">Blog</a>
						<ul class="dropdown">
							<li><a href="<?php echo $this->baseUrl();?>/blog/posts">Posts</a> </li>
							<li><a href="<?php echo $this->baseUrl();?>/pages/page">Page</a> </li>
							</ul>
					</div>
						
                    </li>

	<li>
                        <a href="<?php echo $this->baseUrl();?>/cms/contact/">Contact</a>
                    </li>-->
				               
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div> 
        <!-- /.container -->
    </nav>