<head>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/default/normal.js"></script>
</head>
<div class="fix-header" id="home">
    <div class="w-container">
      <div class="w-nav" data-collapse="medium" data-animation="default" data-duration="400"></div>
    </div>
  </div>
  <div class="fixed-header">
    <div class="w-container container">
      <div class="w-row">

       <!--///////////////////////////////////////////////////////
       // Logo section 
       //////////////////////////////////////////////////////////-->


        <div class="w-col w-col-3 logo">
          <a href="#"><img class="logo" src="<?php echo $this->baseUrl();?>/images/default/aliinfotech-02.png" alt="Netefct"></a>
        </div>

        <!--///////////////////////////////////////////////////////
       // End Logo section 
       //////////////////////////////////////////////////////////-->

        <div class="w-col w-col-9">

       <!--///////////////////////////////////////////////////////
       // Menu section 
       //////////////////////////////////////////////////////////-->


          <div class="w-nav navbar" data-collapse="medium" data-animation="default" data-duration="400" data-contain="1">
            <div class="w-container nav">
              <nav class="w-nav-menu nav-menu" role="navigation">

                <a class="w-nav-link menu-li" href="#home">HOME</a>
                <a class="w-nav-link menu-li" href="#about">ABOUT</a>
                <a class="w-nav-link menu-li" href="#service">SERVICES</a>
                <a class="w-nav-link menu-li" href="#portfolio">PORTFOLIO</a>
                <a class="w-nav-link menu-li"href="#team">TEAM</a>
                <a class="w-nav-link menu-li" href="#contact">CONTACT</a>
              </nav>
              <div class="w-nav-button">
                <div class="w-icon-nav-menu"></div>
              </div>
            </div>
          </div>


          <!--///////////////////////////////////////////////////////
       // End Menu section 
       //////////////////////////////////////////////////////////-->


        </div>
      </div>
    </div>
  </div>