<!-- See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination-->
<?php if ($this->pageCount): ?>
<div class="paginationControl"><!-- Previous page link --> <?php if (isset($this->previous)): ?>
<a class="pagination__page" href="<?php echo  $this->url(array('page' => $this->previous)); ?>">&lt;
Previous</a>  <?php else: ?> <span class="disabled pagination__page">&lt; Previous</span>
 <?php endif; ?> <!-- Numbered page links --> <?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?> <a class="pagination__page"
	href="<?php echo  $this->url(array('page' => $page)); ?>"> <?php echo  $page; ?></a> |
<?php else: ?> <?= $page; ?> | <?php endif; ?><?php endforeach; ?> <!-- Next page link -->
<?php if (isset($this->next)): ?> <a class="pagination__page"
	href="<?= $this->url(array('page' => $this->next)); ?>">Next &gt;</a><?php else: ?>
<span class="disabled pagination__page">Next ></span><?php endif; ?></div>
<?php endif; ?>
