<style>
 .set-table{
 float:left;
 table-layout:fixed;
}
.set-tab{
    margin-top: 8%;
}
</style>  

 <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                         <div class="col-lg-9 col-md-16">
                         <h3></h3>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Edit User</div>
                            
                                </div>
                            </div>
                        </div>
                        
                        <div class="panel-body">
                                <span class="pull-left">Enter Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix">
                                <!-- form accept-charset="UTF-8" action="" method="post" -->
                           <div class="table-responsive set-tab"> 
                           <table class="table table-striped table-bordered table-hover set-table">
                                                <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                                             <tr><td><input type="text" name="video" id="url_video">
                                              </input></td><td>
                                              <?php echo $this->form->url_video ?>     
                                                   
                                                    <tr><td><input type="submit" value="Add" onclick="saveVideo()"/></td><td>
                                            </td></tr>
                                            </table>
                                            </div><!--div responsive end-->
                    <!-- /form --> 
                                
                                
                                </div>
                            </div>
                        
                        <a href="#">
                            <div class="panel-footer">
                            </div>
                        </a>
                    </div>
                </div>
                
                
          
                
                
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



  <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
            $('tr#msg').hide();
            
        <?php  } else{
        ?>
            $('tr#msg').show();
        <?php } ?>
 }


 function saveVideo(){
            var url_video = $('#url_video').val();//select item value from listbox
                    
             if(url_video == "")
{
alert("add video url")
return;
}
               // alert(url_video);
                        $.post("<?php echo $this->baseUrl()?>/index/savev", {url_video: url_video},
                        //this is response from controller
                        function(data){
                           alert(data); 
                       ///     $('#atom').html(data);
                         //   $('#show').show();
                            
                        });
          
            }
 </script>