
 <div class="row">
  <div class="col-md-12">
  <div class="page-title">Clean All Cache</div>
  </div><!-- /.col-md-12-->
 </div><!-- /.row -->

            <div class="row">
            <div class="col-lg-12">
                    <table class="table space-mangead">
                         <tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
                 <tr><td><strong>Press Button To Clean Cache:</strong>  
                 <td><a class="btn btn-danger" href="#" onclick="return confirmClean()" href="">Clean Cache </a></td>
                            </tr>
                  
                     </table>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>

<script language="Javascript" type="text/javascript">
window.onload = function () {
 <?php if(!isset($this->msg)){ ?>
      $('tr#msg').hide();

    <?php  } else{
    ?>
      $('tr#msg').show().delay(3000).hide('slow');

    <?php } ?>
 }
  function confirmClean(){
  var r = confirm("Are you sure to Clean All Cache! " );
  if (r == true) {
  window.location.assign("<?php echo $this->baseUrl(); ?>/admin/setting/clean-cache");    
  } else {
  return false;
  }
  }
 </script>