   <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                       <!-- <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo3"><i class="fa fa-file-o fa-fw"></i> CMS Lists<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo3" class="collapse">
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/posts/index"> Posts</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index">Pages</a>
                            </li>
                            </ul>
                         </li>-->
                   
                      </ul>

   </div>