<script src="<?php echo $this->baseUrl();?>/js/admin/ckeditor/ckeditor.js"></script>

<style>
.space-mangead{
	margin-top: 3%;
}
.set-save-draft{
	float:right; 
	margin: 0px 322px 0px 0px;
}
.set-txt{
	height: 30px;
    width: 258px;
}
#url-label{
	display:none;	
}
.set-slug{
	float:left;
    padding: 3px 6px 0 0;
}
.publish-btn{
margin-right:20px;
}
</style>

<div class="row">
            <div class="col-lg-12">
			<a href="<?php echo $this->baseUrl(); ?>/admin/page/lists"> <i class="btn btn-md btn-primary"> Pages List</i></a>
      </div>           
</div>
<br />

<div class="row">
 <div class="col-md-12">
 <div class="page-title"><strong>Add New Page</strong></div>
</div><!-- /.col-md-12-->
</div><!-- /.row -->


<div class="row">
   <div class="col-lg-12">
                                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
									
                                       	<table class="table space-mangead">

									<tr id='msg'><td colspan='2'><?php echo $this->msg ?></td></tr>
										
									   <?php echo $this->form->title; ?>
									   <tr><td><Label>* Page Url Slug</Label></td><td><p class="set-slug"><?php echo $this->page_url;?></p><?php echo $this->form->url_slug; ?></td></tr>
                                       <tr><td style="width: 230px;"><Label>Upload 800 pixel wide image</Label></td><td><?php echo $this->form->image;?></td></tr>							    
                                         <?php //echo $this->form->description; ?>
                                         
                                         <tr>
                                            <td colspan="2">
                                                <textarea contenteditable="true" cols="80" rows="24" class="form-control" id="description" name="description"></textarea>
                                            </td>
                                         </tr>
                                         
										 <?php echo $this->form->is_comment; ?>
                                       <tr><td colspan="2">
                                        <button class="btn btn-md btn-primary pull-right" value="0" name="submit" type="submit">Publish</button>
										<button class="btn btn-md btn-primary pull-right" style="margin-right: 20px;" value="1" name="submit" type="submit">Save as Draft</button>
										</td></tr>  
									
                                        </table>
                                   </form>
	                            </div>
                            </div>
                    
 <script language="Javascript" type="text/javascript">
window.onload = function () { 
 <?php if(!isset($this->msg)){ ?>
			$('tr#msg').hide();
			
		<?php  } else{
		?>
			$('tr#msg').show();
		<?php } ?>
 
    CKEDITOR.replace('description');
 }

 // make slug from title
$("#title").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);        
});
 
  // make custom slug
$("#url").keyup(function(){ 
        var Text = $(this).val();
        Text = Text.toLowerCase();
        var regExp = /\s+/g;
        Text = Text.replace(regExp,'-');
        $("#url").val(Text);        
});
  </script>