<div class="row">
	<div class="col-md-12">
		<div class="page-title">
			<h1>
				Sliders List
			</h1>
		</div>
	</div>
	<!-- /.col-md-12-->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-md-12">
		<div id="msg">
			<?php echo $this->msg ?>
		</div>
		<div class="clearfix">
		</div>
		<br />
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
				<thead>
					<tr>
						<th style="text-align:center;">
							No.
						</th>
						<th style="text-align:center;">
							Slider Name
						</th>
						<th style="text-align:center;">
							Slide 1
						</th>
						<th style="text-align:center;">
							Slide 2
						</th>
						<th style="text-align:center;">
							Slide 3
						</th>
						<th style="text-align:center;">
							Slide 4
						</th>
						<th style="text-align:center;">
							Slide 5
						</th>
                        <th style="text-align:center;">
							Slide 6
						</th>
                        <th style="text-align:center;">
							Edit
						</th>
					</tr>
				</thead>
				<tbody>
					<?php if (count($this->slider_data)){ 
					   foreach ($this->slider_data as $item): ?>
							<tr>
                                <td style="text-align:center; vertical-align: middle;">
                                    <?php echo $item['slider_id'] ?>
                                </td>
                                <td style="text-align:center; vertical-align: middle;">
                                    <?php echo $item['name'] ?>
                                </td>
                                <td style="text-align:center;">                                    
    									<img width="60" height="50" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide1'] ?>" alt="<?php echo $item['slide1'] ?>" />    								
                                </td>
                                <td style="text-align:center;">
    									<img width="60" height="50" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide2'] ?>" alt="<?php echo $item['slide2'] ?>" />
    							</td>
                                <td style="text-align:center;">
    									<img width="60" height="50" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide3'] ?>" alt="<?php echo $item['slide3'] ?>" />
    							</td>
                                <td style="text-align:center;">
    									<img width="60" height="50" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide4'] ?>" alt="<?php echo $item['slide4'] ?>" />
    							</td>
                                <td style="text-align:center;">
    									<img width="60" height="50" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide5'] ?>" alt="<?php echo $item['slide5'] ?>" />
    							</td>
                                <td style="text-align:center;">
    									<img width="60" height="50" src="<?php echo $this->baseUrl(); ?>/images/user/slides/200X200/<?php echo $item['slide6'] ?>" alt="<?php echo $item['slide6'] ?>" />
    							</td>
                                <td style="text-align:center; vertical-align: middle;">
                                   <a class="btn btn-sm btn-warning float-right" href="<?php echo $this->baseUrl(); ?>/admin/sliders/edit/id/<?php echo $item['slider_id'] ?>">Edit</a>
                                </td>
							</tr>
							<?php endforeach; }?>
				</tbody>
			</table>
		</div>
		<!-- div responsive end-->
	</div>
</div>
<!-- /.row -->
<script>
	
    $(function () {

        <?php if(!isset($this->msg)){ ?>
            $('#msg').hide();

        <?php  } else{
        ?>
            $('#msg').show();
        <?php } ?>
        
        $('#dataTables-example').dataTable();
    });        

</script>