
<div class="row">
 <div class="col-md-12">
 <div class="page-title">Photo Categories List</div>
 </div><!-- /.col-md-12-->
</div><!-- /.row -->
             <div class="row">
                         <div class="col-md-12">

                                       <div class="table-responsive">
                                                     <table cellpadding="0" cellspacing="0" border="0" class="responsive dynamicTable display table table-bordered  set-table" width="100%">
                                                        <thead>
                                                        
                                                            <tr>
                                                                <th style="text-align:center;">Banner</th>
                                                                <th style="text-align:center;">Name</th>
                                                                <th style="text-align:center;">Edit</th>
                                                                <th style="text-align:center;">Delete </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                        <?php if (count($this->paginator)){ ?>

                                                        <?php foreach ($this->paginator as $item): ?>

                                                        <tr class="odd gradeX">
                                                       
                                                        <td style="text-align:center;">
                                                         <div  style="position: relative; width: 50px; height: 50px">
													     <img style="max-width:100%; max-height: 100%" src="<?php echo $this->baseUrl(); ?>/images/user/photo_gallery/categories/200X200/<?php echo $item['banner'] ?>" alt="block-image" />
														 </div>
                                                        </td>
                                                        <td style="text-align:center;">
                                                        <?php echo $item['category_name'] ?>
                                                        </td>
                                                        <td style="text-align:center;">
                                                        <a class="btn btn-sm btn-warning float-right"
                                                        href="<?php echo $this->baseUrl(); ?>/admin/photo-categories/edit/id/<?php echo $item['pg_cat_id'] ?>">
                                                        Edit</a></td>
                                                        <td  style="text-align:center;"><a class="btn btn-danger" href="#" onclick="return confirmDelete(<?php echo $item['pg_cat_id'] ?> )" >Delete </a></td>
                                                        </tr>
                                                            <?php endforeach; ?>
                                                            <tr><td colspan='9' style="text-align:center;">
                                                            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>
                                                            </td>
                                                            </tr><?php } ?>
                                                        </tbody>

                                                        </table>
                                                        </div><!-- div responsive end-->

                                </div>

                  `  </div>
                 <!-- /.row -->

<script>

function confirmDelete(id){
    var r = confirm("Are you sure to Delete this Category! " );
    if (r == true) {
    window.location.assign("<?php echo $this->baseUrl(); ?>/admin/photo-categories/delete-category/id/" + id);    
    } else {
    return false;
    }
    }   
</script>
